In [1]:
from datasets import load_dataset
import pandas as pd

In [2]:
datasets = load_dataset("MongoDB/embedded_movies")

In [3]:
data = pd.DataFrame(datasets['train'])

In [4]:
data.head()

,plot,runtime,genres,fullplot,directors,writers,countries,poster,languages,cast,title,num_mflix_comments,rated,imdb,awards,type,metacritic,plot_embedding
0,Young Pauline is left a lot of money when her ...,199.0,[Action],Young Pauline is left a lot of money when her ...,"[Louis J. Gasnier, Donald MacKenzie]","[Charles W. Goddard (screenplay), Basil Dickey...",[USA],https://m.media-amazon.com/images/M/MV5BMzgxOD...,[English],"[Pearl White, Crane Wilbur, Paul Panzer, Edwar...",The Perils of Pauline,0,None,"{'id': 4465, 'rating': 7.6, 'votes': 744}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.0007293965299999999, -0.026834568000000003,..."
1,A penniless young man tries to save an heiress...,22.0,"[Comedy, Short, Action]",As a penniless man worries about how he will m...,"[Alfred J. Goulding, Hal Roach]",[H.M. Walker (titles)],[USA],https://m.media-amazon.com/images/M/MV5BNzE1OW...,[English],"[Harold Lloyd, Mildred Davis, 'Snub' Pollard, ...",From Hand to Mouth,0,TV-G,"{'id': 10146, 'rating': 7.0, 'votes': 639}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.022837115, -0.022941574000000003, 0.014937..."
2,"Michael ""Beau"" Geste leaves England in disgrac...",101.0,"[Action, Adventure, Drama]","Michael ""Beau"" Geste leaves England in disgrac...",[Herbert Brenon],"[Herbert Brenon (adaptation), John Russell (ad...",[USA],None,[English],"[Ronald Colman, Neil Hamilton, Ralph Forbes, A...",Beau Geste,0,None,"{'id': 16634, 'rating': 6.9, 'votes': 222}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.00023330492999999998, -0.028511643000000003..."
3,"Seeking revenge, an athletic young man joins t...",88.0,"[Adventure, Action]",A nobleman vows to avenge the death of his fat...,[Albert Parker],"[Douglas Fairbanks (story), Jack Cunningham (a...",[USA],https://m.media-amazon.com/images/M/MV5BMzU0ND...,None,"[Billie Dove, Tempe Pigott, Donald Crisp, Sam ...",The Black Pirate,1,None,"{'id': 16654, 'rating': 7.2, 'votes': 1146}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[-0.005927917, -0.033394486, 0.0015323418, -0...."
4,An irresponsible young millionaire changes his...,58.0,"[Action, Comedy, Romance]","The Uptown Boy, J. Harold Manners (Lloyd) is a...",[Sam Taylor],"[Ted Wilde (story), John Grey (story), Clyde B...",[USA],https://m.media-amazon.com/images/M/MV5BMTcxMT...,[English],"[Harold Lloyd, Jobyna Ralston, Noah Young, Jim...",For Heaven's Sake,0,PASSED,"{'id': 16895, 'rating': 7.6, 'votes': 918}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.0059373598, -0.026604708, -0.0070914757000..."

In [5]:
data.shape

(1500, 18)

In [6]:
data.columns

Index(['plot', 'runtime', 'genres', 'fullplot', 'directors', 'writers',
       'countries', 'poster', 'languages', 'cast', 'title',
       'num_mflix_comments', 'rated', 'imdb', 'awards', 'type', 'metacritic',
       'plot_embedding'],
      dtype='object')

In [7]:
data.isnull().sum()

plot                   27
runtime                15
genres                  0
fullplot               48
directors              13
writers                13
countries               0
poster                 89
languages               1
cast                    1
title                   0
num_mflix_comments      0
rated                 308
imdb                    0
awards                  0
type                    0
metacritic            928
plot_embedding         28
dtype: int64

In [8]:
data.isnull().sum().sum()

1471

In [9]:
data = data.dropna(subset=["fullplot"])

In [10]:
data.head()

,plot,runtime,genres,fullplot,directors,writers,countries,poster,languages,cast,title,num_mflix_comments,rated,imdb,awards,type,metacritic,plot_embedding
0,Young Pauline is left a lot of money when her ...,199.0,[Action],Young Pauline is left a lot of money when her ...,"[Louis J. Gasnier, Donald MacKenzie]","[Charles W. Goddard (screenplay), Basil Dickey...",[USA],https://m.media-amazon.com/images/M/MV5BMzgxOD...,[English],"[Pearl White, Crane Wilbur, Paul Panzer, Edwar...",The Perils of Pauline,0,None,"{'id': 4465, 'rating': 7.6, 'votes': 744}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.0007293965299999999, -0.026834568000000003,..."
1,A penniless young man tries to save an heiress...,22.0,"[Comedy, Short, Action]",As a penniless man worries about how he will m...,"[Alfred J. Goulding, Hal Roach]",[H.M. Walker (titles)],[USA],https://m.media-amazon.com/images/M/MV5BNzE1OW...,[English],"[Harold Lloyd, Mildred Davis, 'Snub' Pollard, ...",From Hand to Mouth,0,TV-G,"{'id': 10146, 'rating': 7.0, 'votes': 639}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.022837115, -0.022941574000000003, 0.014937..."
2,"Michael ""Beau"" Geste leaves England in disgrac...",101.0,"[Action, Adventure, Drama]","Michael ""Beau"" Geste leaves England in disgrac...",[Herbert Brenon],"[Herbert Brenon (adaptation), John Russell (ad...",[USA],None,[English],"[Ronald Colman, Neil Hamilton, Ralph Forbes, A...",Beau Geste,0,None,"{'id': 16634, 'rating': 6.9, 'votes': 222}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.00023330492999999998, -0.028511643000000003..."
3,"Seeking revenge, an athletic young man joins t...",88.0,"[Adventure, Action]",A nobleman vows to avenge the death of his fat...,[Albert Parker],"[Douglas Fairbanks (story), Jack Cunningham (a...",[USA],https://m.media-amazon.com/images/M/MV5BMzU0ND...,None,"[Billie Dove, Tempe Pigott, Donald Crisp, Sam ...",The Black Pirate,1,None,"{'id': 16654, 'rating': 7.2, 'votes': 1146}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[-0.005927917, -0.033394486, 0.0015323418, -0...."
4,An irresponsible young millionaire changes his...,58.0,"[Action, Comedy, Romance]","The Uptown Boy, J. Harold Manners (Lloyd) is a...",[Sam Taylor],"[Ted Wilde (story), John Grey (story), Clyde B...",[USA],https://m.media-amazon.com/images/M/MV5BMTcxMT...,[English],"[Harold Lloyd, Jobyna Ralston, Noah Young, Jim...",For Heaven's Sake,0,PASSED,"{'id': 16895, 'rating': 7.6, 'votes': 918}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.0059373598, -0.026604708, -0.0070914757000..."

In [11]:
data = data.drop(columns=["plot_embedding"])

In [12]:
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer("thenlper/gte-large")

In [13]:
def get_embedding(text:str)->list[float]:

  if not text.strip():
    print("attempted to get embedding for empty text.")
    return []

  embedding=embedding_model.encode(text)
  return embedding.tolist()

In [14]:
text = "      Vikas Jangid is a Data Scientist Who create product of data"

In [15]:
text.strip()

'Vikas Jangid is a Data Scientist Who create product of data'

In [16]:
data["embeding"] = data["fullplot"].apply(get_embedding)

KeyboardInterrupt:

In [ ]:
import numpy as np
import pymongo

In [ ]:
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
uri = "mongodb+srv://vikas_008:23MSM40002@cluster0.rus2ded.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))
# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [ ]:
db = client["mongorag"]

In [ ]:
collection = db["mongoragcollection"]

In [ ]:
'''
collection.insert_one(
    {
        "name":"vikas",
        "age":24,
        "city":"jaipur"
    }
)
'''

'\ncollection.insert_one(\n    {\n        "name":"vikas",\n        "age":24,\n        "city":"jaipur"\n    }\n)\n'

In [ ]:
data.head()

,plot,runtime,genres,fullplot,directors,writers,countries,poster,languages,cast,title,num_mflix_comments,rated,imdb,awards,type,metacritic,embeding
0,Young Pauline is left a lot of money when her ...,199.0,[Action],Young Pauline is left a lot of money when her ...,"[Louis J. Gasnier, Donald MacKenzie]","[Charles W. Goddard (screenplay), Basil Dickey...",[USA],https://m.media-amazon.com/images/M/MV5BMzgxOD...,[English],"[Pearl White, Crane Wilbur, Paul Panzer, Edwar...",The Perils of Pauline,0,None,"{'id': 4465, 'rating': 7.6, 'votes': 744}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[-0.00928583461791277, -0.005062106531113386, ..."
1,A penniless young man tries to save an heiress...,22.0,"[Comedy, Short, Action]",As a penniless man worries about how he will m...,"[Alfred J. Goulding, Hal Roach]",[H.M. Walker (titles)],[USA],https://m.media-amazon.com/images/M/MV5BNzE1OW...,[English],"[Harold Lloyd, Mildred Davis, 'Snub' Pollard, ...",From Hand to Mouth,0,TV-G,"{'id': 10146, 'rating': 7.0, 'votes': 639}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.002439377596601844, 0.023095935583114624, ..."
2,"Michael ""Beau"" Geste leaves England in disgrac...",101.0,"[Action, Adventure, Drama]","Michael ""Beau"" Geste leaves England in disgrac...",[Herbert Brenon],"[Herbert Brenon (adaptation), John Russell (ad...",[USA],None,[English],"[Ronald Colman, Neil Hamilton, Ralph Forbes, A...",Beau Geste,0,None,"{'id': 16634, 'rating': 6.9, 'votes': 222}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.012204296886920929, -0.011455753818154335, ..."
3,"Seeking revenge, an athletic young man joins t...",88.0,"[Adventure, Action]",A nobleman vows to avenge the death of his fat...,[Albert Parker],"[Douglas Fairbanks (story), Jack Cunningham (a...",[USA],https://m.media-amazon.com/images/M/MV5BMzU0ND...,None,"[Billie Dove, Tempe Pigott, Donald Crisp, Sam ...",The Black Pirate,1,None,"{'id': 16654, 'rating': 7.2, 'votes': 1146}","{'nominations': 0, 'text': '1 win.', 'wins': 1}",movie,NaN,"[0.004541362170130014, -0.0006100604659877717,..."
4,An irresponsible young millionaire changes his...,58.0,"[Action, Comedy, Romance]","The Uptown Boy, J. Harold Manners (Lloyd) is a...",[Sam Taylor],"[Ted Wilde (story), John Grey (story), Clyde B...",[USA],https://m.media-amazon.com/images/M/MV5BMTcxMT...,[English],"[Harold Lloyd, Jobyna Ralston, Noah Young, Jim...",For Heaven's Sake,0,PASSED,"{'id': 16895, 'rating': 7.6, 'votes': 918}","{'nominations': 1, 'text': '1 nomination.', 'w...",movie,NaN,"[-0.0022256115917116404, 0.011567802168428898,..."

In [ ]:
document = data.to_dict("records")

In [ ]:
collection.insert_many(document)

InsertManyResult([ObjectId('67d176653e0c852849b9bdf6'), ObjectId('67d176653e0c852849b9bdf7'), ObjectId('67d176653e0c852849b9bdf8'), ObjectId('67d176653e0c852849b9bdf9'), ObjectId('67d176653e0c852849b9bdfa'), ObjectId('67d176653e0c852849b9bdfb'), ObjectId('67d176653e0c852849b9bdfc'), ObjectId('67d176653e0c852849b9bdfd'), ObjectId('67d176653e0c852849b9bdfe'), ObjectId('67d176653e0c852849b9bdff'), ObjectId('67d176653e0c852849b9be00'), ObjectId('67d176653e0c852849b9be01'), ObjectId('67d176653e0c852849b9be02'), ObjectId('67d176653e0c852849b9be03'), ObjectId('67d176653e0c852849b9be04'), ObjectId('67d176653e0c852849b9be05'), ObjectId('67d176653e0c852849b9be06'), ObjectId('67d176653e0c852849b9be07'), ObjectId('67d176653e0c852849b9be08'), ObjectId('67d176653e0c852849b9be09'), ObjectId('67d176653e0c852849b9be0a'), ObjectId('67d176653e0c852849b9be0b'), ObjectId('67d176653e0c852849b9be0c'), ObjectId('67d176653e0c852849b9be0d'), ObjectId('67d176653e0c852849b9be0e'), ObjectId('67d176653e0c852849b9be0f'), ObjectId('67d176653e0c852849b9be10'), ObjectId('67d176653e0c852849b9be11'), ObjectId('67d176653e0c852849b9be12'), ObjectId('67d176653e0c852849b9be13'), ObjectId('67d176653e0c852849b9be14'), ObjectId('67d176653e0c852849b9be15'), ObjectId('67d176653e0c852849b9be16'), ObjectId('67d176653e0c852849b9be17'), ObjectId('67d176653e0c852849b9be18'), ObjectId('67d176653e0c852849b9be19'), ObjectId('67d176653e0c852849b9be1a'), ObjectId('67d176653e0c852849b9be1b'), ObjectId('67d176653e0c852849b9be1c'), ObjectId('67d176653e0c852849b9be1d'), ObjectId('67d176653e0c852849b9be1e'), ObjectId('67d176653e0c852849b9be1f'), ObjectId('67d176653e0c852849b9be20'), ObjectId('67d176653e0c852849b9be21'), ObjectId('67d176653e0c852849b9be22'), ObjectId('67d176653e0c852849b9be23'), ObjectId('67d176653e0c852849b9be24'), ObjectId('67d176653e0c852849b9be25'), ObjectId('67d176653e0c852849b9be26'), ObjectId('67d176653e0c852849b9be27'), ObjectId('67d176653e0c852849b9be28'), ObjectId('67d176653e0c852849b9be29'), ObjectId('67d176653e0c852849b9be2a'), ObjectId('67d176653e0c852849b9be2b'), ObjectId('67d176653e0c852849b9be2c'), ObjectId('67d176653e0c852849b9be2d'), ObjectId('67d176653e0c852849b9be2e'), ObjectId('67d176653e0c852849b9be2f'), ObjectId('67d176653e0c852849b9be30'), ObjectId('67d176653e0c852849b9be31'), ObjectId('67d176653e0c852849b9be32'), ObjectId('67d176653e0c852849b9be33'), ObjectId('67d176653e0c852849b9be34'), ObjectId('67d176653e0c852849b9be35'), ObjectId('67d176653e0c852849b9be36'), ObjectId('67d176653e0c852849b9be37'), ObjectId('67d176653e0c852849b9be38'), ObjectId('67d176653e0c852849b9be39'), ObjectId('67d176653e0c852849b9be3a'), ObjectId('67d176653e0c852849b9be3b'), ObjectId('67d176653e0c852849b9be3c'), ObjectId('67d176653e0c852849b9be3d'), ObjectId('67d176653e0c852849b9be3e'), ObjectId('67d176653e0c852849b9be3f'), ObjectId('67d176653e0c852849b9be40'), ObjectId('67d176653e0c852849b9be41'), ObjectId('67d176653e0c852849b9be42'), ObjectId('67d176653e0c852849b9be43'), ObjectId('67d176653e0c852849b9be44'), ObjectId('67d176653e0c852849b9be45'), ObjectId('67d176653e0c852849b9be46'), ObjectId('67d176653e0c852849b9be47'), ObjectId('67d176653e0c852849b9be48'), ObjectId('67d176653e0c852849b9be49'), ObjectId('67d176653e0c852849b9be4a'), ObjectId('67d176653e0c852849b9be4b'), ObjectId('67d176653e0c852849b9be4c'), ObjectId('67d176653e0c852849b9be4d'), ObjectId('67d176653e0c852849b9be4e'), ObjectId('67d176653e0c852849b9be4f'), ObjectId('67d176653e0c852849b9be50'), ObjectId('67d176653e0c852849b9be51'), ObjectId('67d176653e0c852849b9be52'), ObjectId('67d176653e0c852849b9be53'), ObjectId('67d176653e0c852849b9be54'), ObjectId('67d176653e0c852849b9be55'), ObjectId('67d176653e0c852849b9be56'), ObjectId('67d176653e0c852849b9be57'), ObjectId('67d176653e0c852849b9be58'), ObjectId('67d176653e0c852849b9be59'), ObjectId('67d176653e0c852849b9be5a'), ObjectId('67d176653e0c852849b9be5b'), ObjectId('67d176653e0c852849b9be5c'), ObjectId('67d176653e0c852849b9be5d'), ObjectId('67d176653e0c852849b9be5e'), ObjectId('67d176653e0c852849b9be5f'), ObjectId('67d176653e0c852849b9be60'), ObjectId('67d176653e0c852849b9be61'), ObjectId('67d176653e0c852849b9be62'), ObjectId('67d176653e0c852849b9be63'), ObjectId('67d176653e0c852849b9be64'), ObjectId('67d176653e0c852849b9be65'), ObjectId('67d176653e0c852849b9be66'), ObjectId('67d176653e0c852849b9be67'), ObjectId('67d176653e0c852849b9be68'), ObjectId('67d176653e0c852849b9be69'), ObjectId('67d176653e0c852849b9be6a'), ObjectId('67d176653e0c852849b9be6b'), ObjectId('67d176653e0c852849b9be6c'), ObjectId('67d176653e0c852849b9be6d'), ObjectId('67d176653e0c852849b9be6e'), ObjectId('67d176653e0c852849b9be6f'), ObjectId('67d176653e0c852849b9be70'), ObjectId('67d176653e0c852849b9be71'), ObjectId('67d176653e0c852849b9be72'), ObjectId('67d176653e0c852849b9be73'), ObjectId('67d176653e0c852849b9be74'), ObjectId('67d176653e0c852849b9be75'), ObjectId('67d176653e0c852849b9be76'), ObjectId('67d176653e0c852849b9be77'), ObjectId('67d176653e0c852849b9be78'), ObjectId('67d176653e0c852849b9be79'), ObjectId('67d176653e0c852849b9be7a'), ObjectId('67d176653e0c852849b9be7b'), ObjectId('67d176653e0c852849b9be7c'), ObjectId('67d176653e0c852849b9be7d'), ObjectId('67d176653e0c852849b9be7e'), ObjectId('67d176653e0c852849b9be7f'), ObjectId('67d176653e0c852849b9be80'), ObjectId('67d176653e0c852849b9be81'), ObjectId('67d176653e0c852849b9be82'), ObjectId('67d176653e0c852849b9be83'), ObjectId('67d176653e0c852849b9be84'), ObjectId('67d176653e0c852849b9be85'), ObjectId('67d176653e0c852849b9be86'), ObjectId('67d176653e0c852849b9be87'), ObjectId('67d176653e0c852849b9be88'), ObjectId('67d176653e0c852849b9be89'), ObjectId('67d176653e0c852849b9be8a'), ObjectId('67d176653e0c852849b9be8b'), ObjectId('67d176653e0c852849b9be8c'), ObjectId('67d176653e0c852849b9be8d'), ObjectId('67d176653e0c852849b9be8e'), ObjectId('67d176653e0c852849b9be8f'), ObjectId('67d176653e0c852849b9be90'), ObjectId('67d176653e0c852849b9be91'), ObjectId('67d176653e0c852849b9be92'), ObjectId('67d176653e0c852849b9be93'), ObjectId('67d176653e0c852849b9be94'), ObjectId('67d176653e0c852849b9be95'), ObjectId('67d176653e0c852849b9be96'), ObjectId('67d176653e0c852849b9be97'), ObjectId('67d176653e0c852849b9be98'), ObjectId('67d176653e0c852849b9be99'), ObjectId('67d176653e0c852849b9be9a'), ObjectId('67d176653e0c852849b9be9b'), ObjectId('67d176653e0c852849b9be9c'), ObjectId('67d176653e0c852849b9be9d'), ObjectId('67d176653e0c852849b9be9e'), ObjectId('67d176653e0c852849b9be9f'), ObjectId('67d176653e0c852849b9bea0'), ObjectId('67d176653e0c852849b9bea1'), ObjectId('67d176653e0c852849b9bea2'), ObjectId('67d176653e0c852849b9bea3'), ObjectId('67d176653e0c852849b9bea4'), ObjectId('67d176653e0c852849b9bea5'), ObjectId('67d176653e0c852849b9bea6'), ObjectId('67d176653e0c852849b9bea7'), ObjectId('67d176653e0c852849b9bea8'), ObjectId('67d176653e0c852849b9bea9'), ObjectId('67d176653e0c852849b9beaa'), ObjectId('67d176653e0c852849b9beab'), ObjectId('67d176653e0c852849b9beac'), ObjectId('67d176653e0c852849b9bead'), ObjectId('67d176653e0c852849b9beae'), ObjectId('67d176653e0c852849b9beaf'), ObjectId('67d176653e0c852849b9beb0'), ObjectId('67d176653e0c852849b9beb1'), ObjectId('67d176653e0c852849b9beb2'), ObjectId('67d176653e0c852849b9beb3'), ObjectId('67d176653e0c852849b9beb4'), ObjectId('67d176653e0c852849b9beb5'), ObjectId('67d176653e0c852849b9beb6'), ObjectId('67d176653e0c852849b9beb7'), ObjectId('67d176653e0c852849b9beb8'), ObjectId('67d176653e0c852849b9beb9'), ObjectId('67d176653e0c852849b9beba'), ObjectId('67d176653e0c852849b9bebb'), ObjectId('67d176653e0c852849b9bebc'), ObjectId('67d176653e0c852849b9bebd'), ObjectId('67d176653e0c852849b9bebe'), ObjectId('67d176653e0c852849b9bebf'), ObjectId('67d176653e0c852849b9bec0'), ObjectId('67d176653e0c852849b9bec1'), ObjectId('67d176653e0c852849b9bec2'), ObjectId('67d176653e0c852849b9bec3'), ObjectId('67d176653e0c852849b9bec4'), ObjectId('67d176653e0c852849b9bec5'), ObjectId('67d176653e0c852849b9bec6'), ObjectId('67d176653e0c852849b9bec7'), ObjectId('67d176653e0c852849b9bec8'), ObjectId('67d176653e0c852849b9bec9'), ObjectId('67d176653e0c852849b9beca'), ObjectId('67d176653e0c852849b9becb'), ObjectId('67d176653e0c852849b9becc'), ObjectId('67d176653e0c852849b9becd'), ObjectId('67d176653e0c852849b9bece'), ObjectId('67d176653e0c852849b9becf'), ObjectId('67d176653e0c852849b9bed0'), ObjectId('67d176653e0c852849b9bed1'), ObjectId('67d176653e0c852849b9bed2'), ObjectId('67d176653e0c852849b9bed3'), ObjectId('67d176653e0c852849b9bed4'), ObjectId('67d176653e0c852849b9bed5'), ObjectId('67d176653e0c852849b9bed6'), ObjectId('67d176653e0c852849b9bed7'), ObjectId('67d176653e0c852849b9bed8'), ObjectId('67d176653e0c852849b9bed9'), ObjectId('67d176653e0c852849b9beda'), ObjectId('67d176653e0c852849b9bedb'), ObjectId('67d176653e0c852849b9bedc'), ObjectId('67d176653e0c852849b9bedd'), ObjectId('67d176653e0c852849b9bede'), ObjectId('67d176653e0c852849b9bedf'), ObjectId('67d176653e0c852849b9bee0'), ObjectId('67d176653e0c852849b9bee1'), ObjectId('67d176653e0c852849b9bee2'), ObjectId('67d176653e0c852849b9bee3'), ObjectId('67d176653e0c852849b9bee4'), ObjectId('67d176653e0c852849b9bee5'), ObjectId('67d176653e0c852849b9bee6'), ObjectId('67d176653e0c852849b9bee7'), ObjectId('67d176653e0c852849b9bee8'), ObjectId('67d176653e0c852849b9bee9'), ObjectId('67d176653e0c852849b9beea'), ObjectId('67d176653e0c852849b9beeb'), ObjectId('67d176653e0c852849b9beec'), ObjectId('67d176653e0c852849b9beed'), ObjectId('67d176653e0c852849b9beee'), ObjectId('67d176653e0c852849b9beef'), ObjectId('67d176653e0c852849b9bef0'), ObjectId('67d176653e0c852849b9bef1'), ObjectId('67d176653e0c852849b9bef2'), ObjectId('67d176653e0c852849b9bef3'), ObjectId('67d176653e0c852849b9bef4'), ObjectId('67d176653e0c852849b9bef5'), ObjectId('67d176653e0c852849b9bef6'), ObjectId('67d176653e0c852849b9bef7'), ObjectId('67d176653e0c852849b9bef8'), ObjectId('67d176653e0c852849b9bef9'), ObjectId('67d176653e0c852849b9befa'), ObjectId('67d176653e0c852849b9befb'), ObjectId('67d176653e0c852849b9befc'), ObjectId('67d176653e0c852849b9befd'), ObjectId('67d176653e0c852849b9befe'), ObjectId('67d176653e0c852849b9beff'), ObjectId('67d176653e0c852849b9bf00'), ObjectId('67d176653e0c852849b9bf01'), ObjectId('67d176653e0c852849b9bf02'), ObjectId('67d176653e0c852849b9bf03'), ObjectId('67d176653e0c852849b9bf04'), ObjectId('67d176653e0c852849b9bf05'), ObjectId('67d176653e0c852849b9bf06'), ObjectId('67d176653e0c852849b9bf07'), ObjectId('67d176653e0c852849b9bf08'), ObjectId('67d176653e0c852849b9bf09'), ObjectId('67d176653e0c852849b9bf0a'), ObjectId('67d176653e0c852849b9bf0b'), ObjectId('67d176653e0c852849b9bf0c'), ObjectId('67d176653e0c852849b9bf0d'), ObjectId('67d176653e0c852849b9bf0e'), ObjectId('67d176653e0c852849b9bf0f'), ObjectId('67d176653e0c852849b9bf10'), ObjectId('67d176653e0c852849b9bf11'), ObjectId('67d176653e0c852849b9bf12'), ObjectId('67d176653e0c852849b9bf13'), ObjectId('67d176653e0c852849b9bf14'), ObjectId('67d176653e0c852849b9bf15'), ObjectId('67d176653e0c852849b9bf16'), ObjectId('67d176653e0c852849b9bf17'), ObjectId('67d176653e0c852849b9bf18'), ObjectId('67d176653e0c852849b9bf19'), ObjectId('67d176653e0c852849b9bf1a'), ObjectId('67d176653e0c852849b9bf1b'), ObjectId('67d176653e0c852849b9bf1c'), ObjectId('67d176653e0c852849b9bf1d'), ObjectId('67d176653e0c852849b9bf1e'), ObjectId('67d176653e0c852849b9bf1f'), ObjectId('67d176653e0c852849b9bf20'), ObjectId('67d176653e0c852849b9bf21'), ObjectId('67d176653e0c852849b9bf22'), ObjectId('67d176653e0c852849b9bf23'), ObjectId('67d176653e0c852849b9bf24'), ObjectId('67d176653e0c852849b9bf25'), ObjectId('67d176653e0c852849b9bf26'), ObjectId('67d176653e0c852849b9bf27'), ObjectId('67d176653e0c852849b9bf28'), ObjectId('67d176653e0c852849b9bf29'), ObjectId('67d176653e0c852849b9bf2a'), ObjectId('67d176653e0c852849b9bf2b'), ObjectId('67d176653e0c852849b9bf2c'), ObjectId('67d176653e0c852849b9bf2d'), ObjectId('67d176653e0c852849b9bf2e'), ObjectId('67d176653e0c852849b9bf2f'), ObjectId('67d176653e0c852849b9bf30'), ObjectId('67d176653e0c852849b9bf31'), ObjectId('67d176653e0c852849b9bf32'), ObjectId('67d176653e0c852849b9bf33'), ObjectId('67d176653e0c852849b9bf34'), ObjectId('67d176653e0c852849b9bf35'), ObjectId('67d176653e0c852849b9bf36'), ObjectId('67d176653e0c852849b9bf37'), ObjectId('67d176653e0c852849b9bf38'), ObjectId('67d176653e0c852849b9bf39'), ObjectId('67d176653e0c852849b9bf3a'), ObjectId('67d176653e0c852849b9bf3b'), ObjectId('67d176653e0c852849b9bf3c'), ObjectId('67d176653e0c852849b9bf3d'), ObjectId('67d176653e0c852849b9bf3e'), ObjectId('67d176653e0c852849b9bf3f'), ObjectId('67d176653e0c852849b9bf40'), ObjectId('67d176653e0c852849b9bf41'), ObjectId('67d176653e0c852849b9bf42'), ObjectId('67d176653e0c852849b9bf43'), ObjectId('67d176653e0c852849b9bf44'), ObjectId('67d176653e0c852849b9bf45'), ObjectId('67d176653e0c852849b9bf46'), ObjectId('67d176653e0c852849b9bf47'), ObjectId('67d176653e0c852849b9bf48'), ObjectId('67d176653e0c852849b9bf49'), ObjectId('67d176653e0c852849b9bf4a'), ObjectId('67d176653e0c852849b9bf4b'), ObjectId('67d176653e0c852849b9bf4c'), ObjectId('67d176653e0c852849b9bf4d'), ObjectId('67d176653e0c852849b9bf4e'), ObjectId('67d176653e0c852849b9bf4f'), ObjectId('67d176653e0c852849b9bf50'), ObjectId('67d176653e0c852849b9bf51'), ObjectId('67d176653e0c852849b9bf52'), ObjectId('67d176653e0c852849b9bf53'), ObjectId('67d176653e0c852849b9bf54'), ObjectId('67d176653e0c852849b9bf55'), ObjectId('67d176653e0c852849b9bf56'), ObjectId('67d176653e0c852849b9bf57'), ObjectId('67d176653e0c852849b9bf58'), ObjectId('67d176653e0c852849b9bf59'), ObjectId('67d176653e0c852849b9bf5a'), ObjectId('67d176653e0c852849b9bf5b'), ObjectId('67d176653e0c852849b9bf5c'), ObjectId('67d176653e0c852849b9bf5d'), ObjectId('67d176653e0c852849b9bf5e'), ObjectId('67d176653e0c852849b9bf5f'), ObjectId('67d176653e0c852849b9bf60'), ObjectId('67d176653e0c852849b9bf61'), ObjectId('67d176653e0c852849b9bf62'), ObjectId('67d176653e0c852849b9bf63'), ObjectId('67d176653e0c852849b9bf64'), ObjectId('67d176653e0c852849b9bf65'), ObjectId('67d176653e0c852849b9bf66'), ObjectId('67d176653e0c852849b9bf67'), ObjectId('67d176653e0c852849b9bf68'), ObjectId('67d176653e0c852849b9bf69'), ObjectId('67d176653e0c852849b9bf6a'), ObjectId('67d176653e0c852849b9bf6b'), ObjectId('67d176653e0c852849b9bf6c'), ObjectId('67d176653e0c852849b9bf6d'), ObjectId('67d176653e0c852849b9bf6e'), ObjectId('67d176653e0c852849b9bf6f'), ObjectId('67d176653e0c852849b9bf70'), ObjectId('67d176653e0c852849b9bf71'), ObjectId('67d176653e0c852849b9bf72'), ObjectId('67d176653e0c852849b9bf73'), ObjectId('67d176653e0c852849b9bf74'), ObjectId('67d176653e0c852849b9bf75'), ObjectId('67d176653e0c852849b9bf76'), ObjectId('67d176653e0c852849b9bf77'), ObjectId('67d176653e0c852849b9bf78'), ObjectId('67d176653e0c852849b9bf79'), ObjectId('67d176653e0c852849b9bf7a'), ObjectId('67d176653e0c852849b9bf7b'), ObjectId('67d176653e0c852849b9bf7c'), ObjectId('67d176653e0c852849b9bf7d'), ObjectId('67d176653e0c852849b9bf7e'), ObjectId('67d176653e0c852849b9bf7f'), ObjectId('67d176653e0c852849b9bf80'), ObjectId('67d176653e0c852849b9bf81'), ObjectId('67d176653e0c852849b9bf82'), ObjectId('67d176653e0c852849b9bf83'), ObjectId('67d176653e0c852849b9bf84'), ObjectId('67d176653e0c852849b9bf85'), ObjectId('67d176653e0c852849b9bf86'), ObjectId('67d176653e0c852849b9bf87'), ObjectId('67d176653e0c852849b9bf88'), ObjectId('67d176653e0c852849b9bf89'), ObjectId('67d176653e0c852849b9bf8a'), ObjectId('67d176653e0c852849b9bf8b'), ObjectId('67d176653e0c852849b9bf8c'), ObjectId('67d176653e0c852849b9bf8d'), ObjectId('67d176653e0c852849b9bf8e'), ObjectId('67d176653e0c852849b9bf8f'), ObjectId('67d176653e0c852849b9bf90'), ObjectId('67d176653e0c852849b9bf91'), ObjectId('67d176653e0c852849b9bf92'), ObjectId('67d176653e0c852849b9bf93'), ObjectId('67d176653e0c852849b9bf94'), ObjectId('67d176653e0c852849b9bf95'), ObjectId('67d176653e0c852849b9bf96'), ObjectId('67d176653e0c852849b9bf97'), ObjectId('67d176653e0c852849b9bf98'), ObjectId('67d176653e0c852849b9bf99'), ObjectId('67d176653e0c852849b9bf9a'), ObjectId('67d176653e0c852849b9bf9b'), ObjectId('67d176653e0c852849b9bf9c'), ObjectId('67d176653e0c852849b9bf9d'), ObjectId('67d176653e0c852849b9bf9e'), ObjectId('67d176653e0c852849b9bf9f'), ObjectId('67d176653e0c852849b9bfa0'), ObjectId('67d176653e0c852849b9bfa1'), ObjectId('67d176653e0c852849b9bfa2'), ObjectId('67d176653e0c852849b9bfa3'), ObjectId('67d176653e0c852849b9bfa4'), ObjectId('67d176653e0c852849b9bfa5'), ObjectId('67d176653e0c852849b9bfa6'), ObjectId('67d176653e0c852849b9bfa7'), ObjectId('67d176653e0c852849b9bfa8'), ObjectId('67d176653e0c852849b9bfa9'), ObjectId('67d176653e0c852849b9bfaa'), ObjectId('67d176653e0c852849b9bfab'), ObjectId('67d176653e0c852849b9bfac'), ObjectId('67d176653e0c852849b9bfad'), ObjectId('67d176653e0c852849b9bfae'), ObjectId('67d176653e0c852849b9bfaf'), ObjectId('67d176653e0c852849b9bfb0'), ObjectId('67d176653e0c852849b9bfb1'), ObjectId('67d176653e0c852849b9bfb2'), ObjectId('67d176653e0c852849b9bfb3'), ObjectId('67d176653e0c852849b9bfb4'), ObjectId('67d176653e0c852849b9bfb5'), ObjectId('67d176653e0c852849b9bfb6'), ObjectId('67d176653e0c852849b9bfb7'), ObjectId('67d176653e0c852849b9bfb8'), ObjectId('67d176653e0c852849b9bfb9'), ObjectId('67d176653e0c852849b9bfba'), ObjectId('67d176653e0c852849b9bfbb'), ObjectId('67d176653e0c852849b9bfbc'), ObjectId('67d176653e0c852849b9bfbd'), ObjectId('67d176653e0c852849b9bfbe'), ObjectId('67d176653e0c852849b9bfbf'), ObjectId('67d176653e0c852849b9bfc0'), ObjectId('67d176653e0c852849b9bfc1'), ObjectId('67d176653e0c852849b9bfc2'), ObjectId('67d176653e0c852849b9bfc3'), ObjectId('67d176653e0c852849b9bfc4'), ObjectId('67d176653e0c852849b9bfc5'), ObjectId('67d176653e0c852849b9bfc6'), ObjectId('67d176653e0c852849b9bfc7'), ObjectId('67d176653e0c852849b9bfc8'), ObjectId('67d176653e0c852849b9bfc9'), ObjectId('67d176653e0c852849b9bfca'), ObjectId('67d176653e0c852849b9bfcb'), ObjectId('67d176653e0c852849b9bfcc'), ObjectId('67d176653e0c852849b9bfcd'), ObjectId('67d176653e0c852849b9bfce'), ObjectId('67d176653e0c852849b9bfcf'), ObjectId('67d176653e0c852849b9bfd0'), ObjectId('67d176653e0c852849b9bfd1'), ObjectId('67d176653e0c852849b9bfd2'), ObjectId('67d176653e0c852849b9bfd3'), ObjectId('67d176653e0c852849b9bfd4'), ObjectId('67d176653e0c852849b9bfd5'), ObjectId('67d176653e0c852849b9bfd6'), ObjectId('67d176653e0c852849b9bfd7'), ObjectId('67d176653e0c852849b9bfd8'), ObjectId('67d176653e0c852849b9bfd9'), ObjectId('67d176653e0c852849b9bfda'), ObjectId('67d176653e0c852849b9bfdb'), ObjectId('67d176653e0c852849b9bfdc'), ObjectId('67d176653e0c852849b9bfdd'), ObjectId('67d176653e0c852849b9bfde'), ObjectId('67d176653e0c852849b9bfdf'), ObjectId('67d176653e0c852849b9bfe0'), ObjectId('67d176653e0c852849b9bfe1'), ObjectId('67d176653e0c852849b9bfe2'), ObjectId('67d176653e0c852849b9bfe3'), ObjectId('67d176653e0c852849b9bfe4'), ObjectId('67d176653e0c852849b9bfe5'), ObjectId('67d176653e0c852849b9bfe6'), ObjectId('67d176653e0c852849b9bfe7'), ObjectId('67d176653e0c852849b9bfe8'), ObjectId('67d176653e0c852849b9bfe9'), ObjectId('67d176653e0c852849b9bfea'), ObjectId('67d176653e0c852849b9bfeb'), ObjectId('67d176653e0c852849b9bfec'), ObjectId('67d176653e0c852849b9bfed'), ObjectId('67d176653e0c852849b9bfee'), ObjectId('67d176653e0c852849b9bfef'), ObjectId('67d176653e0c852849b9bff0'), ObjectId('67d176653e0c852849b9bff1'), ObjectId('67d176653e0c852849b9bff2'), ObjectId('67d176653e0c852849b9bff3'), ObjectId('67d176653e0c852849b9bff4'), ObjectId('67d176653e0c852849b9bff5'), ObjectId('67d176653e0c852849b9bff6'), ObjectId('67d176653e0c852849b9bff7'), ObjectId('67d176653e0c852849b9bff8'), ObjectId('67d176653e0c852849b9bff9'), ObjectId('67d176653e0c852849b9bffa'), ObjectId('67d176653e0c852849b9bffb'), ObjectId('67d176653e0c852849b9bffc'), ObjectId('67d176653e0c852849b9bffd'), ObjectId('67d176653e0c852849b9bffe'), ObjectId('67d176653e0c852849b9bfff'), ObjectId('67d176653e0c852849b9c000'), ObjectId('67d176653e0c852849b9c001'), ObjectId('67d176653e0c852849b9c002'), ObjectId('67d176653e0c852849b9c0

# **Data Retrival**

In [ ]:
'''
{
  "mappings": {
    "fields": {
      "embeding": {
        "type": "knnVector",
        "dimensions": 1024,
        "similarity": "cosine"
      }
    }
  }
}


'''

'\n{\n  "mappings": {\n    "dynamic": true,\n    "fields": {\n      "embedding": {\n        "type": "knnVector",\n        "dimensions": 1024,\n        "similarity": "cosine"\n      }\n    }\n  }\n}\n\n'

In [ ]:
user_query="what is the best horror movie?"

In [ ]:
query_embedding=get_embedding(user_query)

In [ ]:
print(query_embedding)

[0.0320083424448967, -0.016375744715332985, -0.03466122969985008, 0.001408358453772962, -0.0016439580358564854, -0.012208453379571438, -0.015490722842514515, 0.040277332067489624, -0.00830091256648302, 0.02735944651067257, 0.03242095932364464, -0.007007712963968515, 0.014090856537222862, -0.03207636624574661, -0.008688398636877537, -0.028137385845184326, -0.03549746051430702, -0.023128382861614227, -0.02152186632156372, 0.010077070444822311, -0.008985674008727074, 0.0067076655104756355, -0.06067964434623718, -0.013847094029188156, -0.020732076838612556, 0.016766954213380814, 0.023988083004951477, -0.011809718795120716, 0.0367332398891449, 0.08142606168985367, 0.00792068149894476, -0.041727010160684586, 0.0431947261095047, -0.0383475236594677, -0.028009746223688126, -0.018966885283589363, 0.06600959599018097, -0.0005763508379459381, -0.021067513152956963, -0.03700759634375572, 0.02019067294895649, 0.002797143766656518, 0.05587856099009514, -0.009170591831207275, -0.04668897017836571, -0.008952190168201923, 0.027583837509155273, -0.015085374936461449, 0.0017160504357889295, -0.043774187564849854, -0.0013343192404136062, -0.029875818639993668, 0.01652519404888153, 0.017629260197281837, -0.0032607377506792545, 0.019653668627142906, -0.025073394179344177, -0.008535760454833508, 0.00541295763105154, 0.032042305916547775, 0.03386679291725159, -0.014819731935858727, 0.02971484698355198, -0.03202426806092262, 0.010879469104111195, 0.02332884818315506, 0.01556411013007164, -0.022306367754936218, 0.02760193683207035, 0.02337300404906273, 0.021049320697784424, 0.002065939363092184, -0.01805458776652813, 0.034766584634780884, 0.0030251091811805964, 0.03741617873311043, -0.01573784276843071, 0.029695730656385422, 0.0006013431120663881, -0.015980606898665428, 0.0007810774259269238, 0.04673541709780693, 0.020954910665750504, 0.02021046169102192, -0.05185906961560249, -0.03179566562175751, -0.022550784051418304, 0.01837066560983658, -0.012760680168867111, 0.03453085571527481, 0.02636926807463169, 0.037465933710336685, 0.015783606097102165, -0.022525327280163765, 0.05908160284161568, 0.0466601736843586, -0.029154833406209946, -0.004611938260495663, 0.0025265610311180353, -0.016521859914064407, 0.005954240448772907, 0.03130736202001572, 0.00850889552384615, 0.040518682450056076, -0.03147358447313309, -0.017474524676799774, 0.026919880881905556, -0.009386311285197735, -0.020911354571580887, -0.06331401318311691, 0.00048605355550535023, -0.02724241092801094, 0.017659110948443413, 0.010228575207293034, -0.011343919672071934, 0.025111081078648567, -0.001361762173473835, 0.05826789140701294, -0.053542450070381165, 0.02765336073935032, 0.03721355274319649, 0.0005469390889629722, 0.04296817258000374, -0.02462138794362545, 0.0383731834590435, -0.05155013129115105, 0.002867826959118247, 0.04243101552128792, -0.030731458216905594, -0.0076096877455711365, 0.011489911936223507, -0.02588304691016674, -0.0030866998713463545, 0.049777645617723465, 0.0057975067757070065, 0.014803332276642323, -0.0014377494808286428, -0.014330712147057056, 0.029788410291075706, -0.05668391287326813, 0.027582956477999687, 0.02907949686050415, 0.011499293148517609, 0.07020418345928192, -0.0038389484398066998, -0.015898864716291428, -0.0037641976960003376, 0.009256444871425629, -0.006592717953026295, 0.029001260176301003, -0.01717139221727848, 0.0035949847660958767, -0.011424299329519272, 0.005475966725498438, -0.002744322642683983, -0.01067501399666071, -0.026074901223182678, 0.015689298510551453, 0.02512483298778534, 0.059923313558101654, 0.03004717081785202, -0.00023314634745474905, -0.019350510090589523, 0.030535606667399406, -0.006786858197301626, 0.042349789291620255, -0.018907302990555763, 0.002170208375900984, -0.019379355013370514, -0.01665262132883072, 0.01344323344528675, 0.01091648731380701, 0.009990667924284935, 0.010918762534856796, 0.014142224565148354, 0.05359058454632759, 0.04675549641251564, -0.023213546723127365, 0.05315316095948219, 0.038327597081661224, -0.03136254847049713, -0.011219175532460213, -0.010264020413160324, 0.0847674161195755, -0.028249770402908325, -0.023977430537343025, 0.02091619372367859, -0.043898195028305054, -0.04698707535862923, -0.02380550652742386, -0.05064696818590164, 0.018546193838119507, -0.01723472774028778, 0.025632115080952644, 0.00038849300472065806, 0.01727546565234661, -0.01997288316488266, -0.0026897049974650145, -0.007493643555790186, -0.037110377103090286, -0.00423038424924016, 0.07117007672786713, -0.03158429637551308, 0.026847880333662033, 0.01658271998167038, -0.04171636700630188, 0.0275082066655159, 0.06431133300065994, -0.02559949830174446, -0.02757067047059536, 0.014944636262953281, -0.014692195691168308, 0.013505752198398113, 0.005856485106050968, -0.03337873890995979, 0.008211865089833736, -0.022219128906726837, 0.0487479604780674, -0.022764356806874275, 0.04168066754937172, -0.016766250133514404, 0.01957777328789234, 0.031491030007600784, 0.024465691298246384, 0.00486378138884902, -0.009584885090589523, 0.026308678090572357, 0.03261300176382065, -0.02014349028468132, 0.017161738127470016, 0.011971837840974331, 0.05356650426983833, 0.03546484187245369, 0.029391275718808174, 0.015586011111736298, -0.006758895702660084, 0.04806089401245117, 0.005973175633698702, -0.01746189035475254, 0.03106946311891079, -0.018110422417521477, -0.0322912372648716, 0.04348602145910263, 0.031048214063048363, -0.011675718240439892, 0.03663167729973793, -0.017612893134355545, -0.028673864901065826, -0.043669793754816055, 0.012512006796896458, 0.022035617381334305, 0.030802331864833832, 0.03942194581031799, 0.018589362502098083, -0.01379009522497654, 0.031241709366440773, 0.03165937960147858, 0.06295470148324966, -0.017452504485845566, 0.002383595332503319, -0.04541053995490074, 0.02017878368496895, 0.020895741879940033, 0.016896996647119522, 0.05192938446998596, 0.010108989663422108, -0.01633109152317047, -0.006542179733514786, -0.036948055028915405, -0.06644240766763687, -0.022229958325624466, -0.03849167376756668, -0.02320712059736252, -0.029820507392287254, -0.042382579296827316, 0.004229973070323467, 0.0270598866045475, -0.01314813643693924, 0.0024370155297219753, -0.011577483266592026, -0.02443179115653038, -0.01168095599859953, 0.0009941031457856297, 0.021299319341778755, 0.0017651882953941822, 0.03785668686032295, -0.03670325502753258, 0.03869473561644554, -0.02452237904071808, 0.041068337857723236, -0.013157437555491924, 0.0009884245228022337, -0.010273301973938942, 0.0026115025393664837, 0.03774023801088333, -0.000873041630256921, -0.026039080694317818, -0.020804161205887794, -0.016539307311177254, -0.05507824197411537, 0.018804378807544708, -0.020810000598430634, -0.02760900743305683, -0.0008206652128137648, -0.005096795968711376, 0.034677911549806595, 0.034666068851947784, -0.004415928386151791, 0.048831600695848465, 0.039309386163949966, -0.04362417012453079, 0.04336019232869148, -0.0018112892284989357, 0.010678719729185104, -0.05161832273006439, 0.06915754079818726, 0.023167306557297707, 0.009067995473742485, -0.005265357904136181, 0.03295065462589264, -0.01151389442384243, 0.007077900692820549, 0.017329664900898933, -0.025086689740419388, -0.03141149878501892, 0.04388609156012535, 0.008435872383415699, -0.04090365767478943, 0.02344156615436077, -0.02447027526795864, -0.012635264545679092, -0.02820139192044735, -0.03384595736861229, 0.04022417962551117, 0.029266562312841415, 0.058321334421634674, -0.031980741769075394, -0.04916398599743843, -0.029189379885792732, 0.03462391346693039, 0.04478516802191734, -0.016980715095996857, 0.014332020655274391, 0.03749688342213631, 0.010962436906993389, 0.011340156197547913, 0.006958985701203346, -0.0160723514854908, 0.030212489888072014, -0.002788333687931299, -0.008492770604789257, -0.019293813034892082, 0.005968060810118914, -0.023891905322670937, 0.0211760513484478, 0.034962303936481476, -0.013817868195474148, 0.043413370847702026, -0.005783054046332836, 0.02471337653696537, 0.03472552075982094, 0.012161961756646633, -0.011888756416738033, 0.01190528366714716, -0.05104305222630501, -0.05877649411559105, 0.025075091049075127, -0.0030087020713835955, 0.05355745926499367, -0.046275582164525986, 0.07040638476610184, 0.0034071195404976606, -0.03841284289956093, 0.047193851321935654, -0.036148134618997574, 0.03721557930111885, -0.000702821824233979, -0.021172648295760155, 0.009281521663069725, -0.014774389564990997, 0.00975731946527958, -0.005283179227262735, 0.05101078376173973, 0.06840943545103073, 0.0052963076159358025, 0.0557488352060318, -0.035592179745435715, -0.0420353040099144, -0.027692323550581932, 0.0016471887938678265, -0.012150184251368046, -0.031281642615795135, 0.03884274885058403, -0.025297347456216812, -0.0743415579199791, -0.055178988724946976, 0.035426296293735504, 0.0313832126557827, 0.02538769505918026, -0.03009837493300438, 0.004661615937948227, -0.026430267840623856, 0.0014811329310759902, 0.034536417573690414, -0.007776671089231968, 0.03706560656428337, -0.022990839555859566, 0.0476495698094368, 0.005677445326000452, -0.012236996553838253, -0.01718643121421337, -0.006582993548363447, -0.049589913338422775, 0.0371844545006752, -0.007009486667811871, -0.011384308338165283, -0.014562907628715038, 0.013777950778603554, 0.019915400072932243, 0.031234167516231537, -0.027532272040843964, -0.0015113296685740352, -0.0005703953211195767, 0.024375207722187042, 0.007497434504330158, -0.07129085063934326, 0.0008248795056715608, -0.04212254285812378, 0.044047027826309204, 0.05054447054862976, -0.012897289358079433, -0.029765043407678604, -0.019555121660232544, -0.03677170351147652, -0.07175544649362564, 0.0023794877342879772, 0.04682139679789543, -0.017925728112459183, 0.03190774470567703, -0.05961049720644951, 0.009439947083592415, -0.006856740452349186, 0.00505812419578433, -0.02489861659705639, -0.013754216022789478, 0.024394983425736427, 0.0102540273219347, 0.037622950971126556, -0.010332196019589901, -0.03212360292673111, -0.01960548758506775, -0.06210530549287796, -0.020261161029338837, 0.02430553361773491, -0.03190204128623009, 0.040372952818870544, 0.03744795173406601, 0.006455630995333195, 0.04844566434621811, -0.03290778025984764, 0.06250670552253723, -0.048458270728588104, 0.026311025023460388, -0.018425768241286278, -0.039832357317209244, 0.04776257649064064, 0.027592960745096207, -0.01726972870528698, 0.030579060316085815, 0.00018109512166120112, 0.00663810595870018, 0.00043142159120179713, 0.04981876164674759, -0.04435676336288452, 0.04552780091762543, -0.05258850008249283, -0.003719317726790905, 0.006289239972829819, -0.021181607618927956, 0.020467609167099, -0.037510089576244354, 0.02529485709965229, 0.005903095938265324, 0.02284485287964344, -0.03692356124520302, -0.024557672441005707, -0.019009575247764587, -0.01748567447066307, 0.009114529937505722, -0.029008256271481514, 0.01258805487304926, 0.0127169294282794, -0.03601308539509773, -0.016410313546657562, -0.0037124971859157085, 0.0045406026765704155, 0.000492316554300487, 0.019713424146175385, -0.014879196882247925, 0.022656995803117752, -0.01587606780230999, -0.00734326709061861, -0.025499407202005386, -0.0001187600355478935, 0.017177456989884377, -0.00990025419741869, -0.07488550990819931, 0.007931302301585674, -0.04206107184290886, -0.006222484167665243, -0.031143704429268837, 0.010301885195076466, -0.04532899335026741, 0.0568620041012764, 0.021757397800683975, 0.04308453947305679, -0.0016997656784951687, -0.0033718908671289682, -0.036721281707286835, 0.030745498836040497, -0.01123484130948782, -0.02500445954501629, -0.03705909848213196, 0.03834381327033043, -0.016250165179371834, 0.042397983372211456, -0.0014444420812651515, -0.013778354041278362, -0.08461396396160126, -0.036510419100522995, 0.004832334350794554, -0.03136291354894638, -0.006644131615757942, -0.02927999757230282, -0.0427284799516201, -0.018359271809458733, 0.011553006246685982, 0.014389647170901299, -0.010743319056928158, -0.02447650209069252, -0.026719536632299423, -0.02576439268887043, 0.019049564376473427, -0.025418708100914955, -0.021218786016106606, 0.007712254300713539, -0.015075129456818104, 0.07588324695825577, -0.016935518011450768, 0.045263439416885376, -0.0053776283748447895, 0.020906595513224602, 0.006312479265034199, -0.021086979657411575, -0.056575506925582886, -0.01390744373202324, 0.005273627117276192, -0.00817602314054966, -0.022898701950907707, 0.024588236585259438, -0.050250712782144547, 0.020176388323307037, -0.06626734137535095, 0.004980497527867556, -0.009706691838800907, -0.008748915046453476, -0.0023804972879588604, -0.0022723290603607893, 0.05410037189722061, -0.04054516553878784, -0.015219813212752342, 0.0006153717404231429, 0.04163182154297829, 0.09947853535413742, -0.002271209144964814, -0.0324297770857811, -0.020489677786827087, -0.019243065267801285, -0.05113944038748741, 0.03829090669751167, -0.057175230234861374, -0.005888715386390686, -0.042922619730234146, 0.0045088245533406734, 0.06346166133880615, -0.015053275041282177, 0.048860058188438416, 0.05511259287595749, -0.0073094055987894535, 0.015055014751851559, -0.002909551141783595, -0.004268261604011059, 0.059698205441236496, -0.06363613903522491, 0.011518580839037895, -0.007344154175370932, -0.037022627890110016, -0.01228577271103859, -0.05847303569316864, -0.06695906817913055, -0.05666105076670647, 0.015511236153542995, 0.10456277430057526, -0.03713817149400711, 0.03968307375907898, -0.023728806525468826, -0.06883622705936432, -0.03938069939613342, 0.045483898371458054, -0.0071067227981984615, 0.008725282736122608, 0.041644301265478134, 0.030391374602913857, -0.049646127969026566, -0.03290489688515663, 0.03081207536160946, 0.006639367435127497, -0.024464156478643417, 0.055108796805143356, 0.0034251122269779444, -0.03958489000797272, 0.051503486931324005, 0.029832934960722923, -0.05653258413076401, -0.04627024382352829, -0.004468563944101334, 0.018721556290984154, 0.004193719010800123, -0.034069836139678955, 0.021832183003425598, -0.02953457273542881, 0.00727311335504055, -0.013666505925357342, 0.029788058251142502, -0.030600469559431076, 0.029443612322211266, 0.045716892927885056, 0.004005645401775837, -0.037112317979335785, 0.01418912224471569, -0.018103137612342834, 0.008664081804454327, -0.04184175282716751, -0.0316946841776371, -0.037789300084114075, 0.01682755909860134, -0.01194294448941946, 0.025110037997364998, -0.0023683952167630196, 0.0003362382703926414, 0.027135401964187622, -0.011198051273822784, 0.08165597170591354, 0.008485757745802402, -0.02467392571270466, 0.0013488719705492258, -0.034031737595796585, -0.0620630718767643, -0.04878371208906174, 0.019035089761018753, 0.016332022845745087, -0.0009149994002655149, -0.052474942058324814, 0.011258181184530258, 0.009756539016962051, -0.018441788852214813, 0.005976763553917408, -0.06315348297357559, -0.019527362659573555, -0.05885957553982735, -0.026832927018404007, -0.008003424853086472, -0.0011318705510348082, -0.020799286663532257, 0.02007555402815342, 0.014112435281276703, -0.02826026640832424, 0.022664126008749008, -0.012251623906195164, -0.008958147838711739, 0.006114664487540722, -0.04157061129808426, 0.038767121732234955, -0.027989771217107773, -0.04241245612502098, -0.015379036776721478, 0.03176546469330788, -0.0075175273232162, -0.0019089282723143697, -0.014084957540035248, 0.003383966162800789, -0.002754698973149061, 0.014463178813457489, -0.015995917841792107, 0.01315358281135559, -0.0052152471616864204, -0.0015100468881428242, 0.006563739851117134, 0.030717767775058746, -0.00033816584618762136, 0.05242040008306503, 0.008169935084879398, 0.0034865201450884342, 0.031300321221351624, 0.0025663531851023436, -0.040863484144210815, -0.012602091766893864, 0.01438999641686678, -0.015165182761847973, 0.01941809058189392, -0.03647715970873833, -0.03424398973584175, -0.04160664603114128, -0.048555515706539154, 0.03014330565929413, 0.030628222972154617, 0.022341111674904823, -0.023182177916169167, 0.029187381267547607, 0.01457221433520317, 0.05364776402711868, -0.01600802317261696, 0.021083490923047066, 0.011115391738712788, 0.013054749928414822, 0.022361358627676964, -0.0371062308549881, 0.029531674459576607, 0.03048543632030487, 0.020724404603242874, -0.052068132907152176, -0.013789583928883076, -0.025388678535819054, 0.019733650609850883, 0.026087528094649315, -0.02066016010940075, -0.023639552295207977, -0.04114953428506851, -0.03856310620903969, -0.0017569793853908777, 0.04974503815174103, 0.0016182772815227509, -0.010968800634145737, 0.030100110918283463, -0.03711297735571861, -0.06316845864057541, 0.018041593953967094, -0.04957374930381775, 0.0051259370520710945, 0.011303854174911976, 0.013548933900892735, -0.017104556784033775, -0.05188154801726341, -0.06297958642244339, 0.01404293067753315, -0.01603006012737751, 0.021975472569465637, 0.003758332459256053, 0.025800390169024467, -0.02828756347298622, 0.07017369568347931, -0.0077920644544065, -0.00460459291934967, 0.0017548116156831384, 0.0739016979932785, -0.04745842516422272, -0.006214109715074301, 0.011195260100066662, -0.015644561499357224, 0.022589994594454765, -0.007686321157962084, -0.0005506331217475235, 0.0038528484292328358, 0.008227579295635223, 0.023766860365867615, -0.021382087841629982, 0.016736481338739395, -0.013744289986789227, 0.0006771243643015623, 0.01989387720823288, -0.016554970294237137, -0.015912264585494995, 0.0302734337747097, 0.019155938178300858, -0.005888775922358036, -0.050434812903404236, 0.03606821224093437, 0.031460393220186234, -0.0017039801459759474, 0.04221430793404579, 0.028883010149002075, 0.0744607001543045, -0.0021531505044549704, 0.015405035577714443, -0.00235672271810472, 0.04595623537898064, -0.016405533999204636, 0.022424979135394096, 0.008051188662648201, 0.01006105076521635, 0.03169861063361168, -0.00784696452319622, -0.009791656397283077, 0.04016551747918129, 0.01866108365356922, -0.03460425138473511, -0.013666552491486073, 0.017355037853121758, 0.013359740376472473, -0.013101809658110142, 0.0067056710831820965, -0.001660614856518805, 0.0006718583172187209, 0.0019553436432033777, 0.0033854846842586994, 0.010304763913154602, 0.07004938274621964, -0.022485360503196716, -0.020734146237373352, -0.01289551705121994, -0.012766686268150806, 0.03132626414299011, 0.06282223761081696, 0.0006523940828628838, 0.010830886662006378, 0.027946747839450836, 0.03305118530988693, -0.031768716871738434, 0.03918157517910004, 0.045093584805727005, 0.0036893109790980816, -0.005855646915733814, 0.009873555973172188, 0.030747786164283752, -0.027804989367723465, -0.04286154732108116, -0.004389178939163685, -0.028925344347953796, 0.03075181506574154, -0.0037384082097560167, -0.010019253008067608, 0.0649939700961113, -0.05315004289150238, 0.006764773745089769, -0.0831901878118515, 0.029389461502432823, -0.035002972930669785, -0.01674967259168625, 0.041973091661930084, 0.005350756458938122, -0.0039594764821231365, -0.01909734308719635, 0.009515015408396721, 0.0374942347407341, -0.013465924188494682, 0.024685446172952652, -0.032435543835163116, 0.02153845876455307, 0.006090891547501087, -0.02511063776910305, -0.026674173772335052, 0.025933166965842247, -0.007551237475126982, -0.053541429340839386, -0.0001823556376621127, -0.052354298532009125, 0.0009750648750923574, -0.006890530232340097, -0.036300189793109894, -0.00864892452955246, 0.03015822358429432, -0.02276628650724888, -0.05710875242948532, -0.014044179581105709, 0.010318656452000141, -0.07134227454662323, -0.005842373240739107, 0.018024632707238197, 0.019099466502666473, 0.015222800895571709, -0.014102418906986713, -0.046139273792505264, -0.034853558987379074, -0.020546836778521538, -0.011953471228480339, 0.04122938588261604, -0.014879124239087105, 0.002500426722690463, -0.016286689788103104, -0.052201468497514725, -0.03070923127233982, -0.049869537353515625, -0.0028112323489040136, -0.01398773118853569, 0.048653412610292435, 0.05671069398522377, -0.006152620539069176, -0.019031381234526634, -0.013556758873164654, -0.00045089737977832556, -0.0156328380107

In [ ]:
pipeline = [

    {
        "$vectorSearch": {
            "index": "vector_index",
            "queryVector": query_embedding,
            "path": "embedding",
            "numCandidates": 150,  # Number of candidate matches to consider
            "limit": 4,  # Return top 4 matches
        }
    },
    {
        "$project": {
            "fullplot": 1,  # Include the plot field
            "title": 1,  # Include the title field
            "genres": 1,  # Include the genres field
            "score": {"$meta": "vectorSearchScore"},  # Include the search score
        }
    }
]

In [ ]:
collection.aggregate(pipeline)

In [ ]:
list(collection.aggregate(pipeline))

[]

In [ ]:
def get_embedding(text:str)->list[float]:

  if not text.strip():
    print("attempted to get embedding for empty text.")
    return []

  embedding=embedding_model.encode(text)
  return embedding.tolist()

In [ ]:
def vector_search(user_query,collection):

  query_embedding=get_embedding(user_query)
  print(query_embedding)

  if query_embedding is None:
    return "Invalid query or embeddig is failed"

  pipeline=[

            {
                "$vectorSearch":{

                "index": "vector_index",
                "queryVector": query_embedding,
                "path": "embedding",
                "numCandidates": 150,  # Number of candidate matches to consider
                "limit": 4,  # Return top 4 matches


                }

            },

              {
                 "$project":{

                "fullplot": 1,  # Include the plot field
                "title": 1,  # Include the title field
                "genres": 1,  # Include the genres field
                "score": {"$meta": "vectorSearchScore"},  # Include the search score
                 }

            }

           ]

  result=collection.aggregate(pipeline)
  return list(result)

In [ ]:
vector_search("what is the best horror movie to watch and why?",collection)

[0.019185921177268028, -0.015472998842597008, -0.03955463692545891, 0.002369282301515341, -0.0026591995265334845, 0.005181849468499422, -0.007513169664889574, 0.04510665312409401, -0.018112152814865112, 0.042973391711711884, 0.01343401987105608, -0.0028707829769700766, 0.005479617975652218, -0.031249191612005234, -0.0040832762606441975, -0.031060393899679184, -0.04105724021792412, -0.030109740793704987, -0.03216371312737465, 0.027480358257889748, -0.0031675698701292276, 0.01684349775314331, -0.04414497688412666, -0.02399815246462822, -0.015581835061311722, 0.017874479293823242, 0.02161523886024952, -0.03042467124760151, 0.04588271304965019, 0.07223066687583923, 0.0023236689157783985, -0.04596634581685066, 0.026177139952778816, -0.048973821103572845, -0.03348345682024956, -0.010094995610415936, 0.0548892468214035, 0.0015839148545637727, -0.0027255131863057613, -0.038032565265893936, 0.01665717177093029, 0.014302357099950314, 0.04556028172373772, -0.011216177605092525, -0.05046369507908821, 0.0023861045483499765, 0.017925534397363663, -0.030081860721111298, -0.007713163737207651, -0.021677710115909576, 0.0025280362460762262, -0.03760185092687607, 0.011060122400522232, 0.006693254690617323, 0.013570711016654968, 0.02686602994799614, -0.011295484378933907, -0.013143062591552734, 0.00019356614211574197, 0.04410506412386894, 0.021538356319069862, -0.021799027919769287, 0.024568935856223106, -0.0283063892275095, 0.015344264917075634, 0.024441977962851524, 0.010560423135757446, -0.030671698972582817, 0.028781559318304062, 0.033182621002197266, 0.01933882012963295, -0.0029937559738755226, -0.019163787364959717, 0.01936383917927742, 0.01144575234502554, 0.02072315104305744, -0.01135884877294302, 0.027792207896709442, -0.015587683767080307, -0.020335961133241653, 0.01052192971110344, 0.05448819324374199, 0.021207375451922417, 0.015374410897493362, -0.0703800767660141, -0.04530000314116478, -0.017124861478805542, 0.02929656207561493, -0.014126786030828953, 0.0382278673350811, 0.03566664457321167, 0.027214163914322853, 0.011118213646113873, -0.032380275428295135, 0.04557011276483536, 0.05568910390138626, -0.03874795138835907, -0.005883869715034962, 0.0031911595724523067, -0.017282329499721527, 0.005285183433443308, 0.04445952922105789, -0.0044273920357227325, 0.028387324884533882, -0.03157701715826988, -0.005482749547809362, 0.02533877082169056, -0.004885320086032152, -0.024914715439081192, -0.05109068751335144, -0.007489930838346481, -0.036728985607624054, 0.00919526256620884, 0.010751624591648579, -0.011365924961864948, 0.03295490890741348, -0.004312330391258001, 0.04387517273426056, -0.059020426124334335, 0.02311747521162033, 0.01511062029749155, -0.00029512454057112336, 0.054292403161525726, -0.031850673258304596, 0.05932876095175743, -0.04194685444235802, -0.007042129524052143, 0.03700248524546623, -0.03655996173620224, -0.006839779671281576, -0.002326343907043338, -0.02935059554874897, 0.0031672262120991945, 0.04241705685853958, 0.01748664677143097, 0.015422792173922062, -0.0034261082764714956, -0.0076525029726326466, 0.024394555017352104, -0.051861438900232315, 0.042092952877283096, 0.006301604676991701, 0.008150339126586914, 0.07824896275997162, 0.007197103463113308, -0.008467086590826511, 0.018384108319878578, -0.008630882948637009, -0.008001118898391724, 0.03481711819767952, -0.0060943919233977795, 0.0023830533027648926, 0.005015701986849308, 0.018067052587866783, -0.01355196163058281, -0.023615287616848946, -0.021410604938864708, 0.020231517031788826, 0.00884122122079134, 0.06210235878825188, 0.04051230102777481, 0.022513380274176598, -0.03465414419770241, 0.038845986127853394, -0.002171834697946906, 0.04867856204509735, -0.03257758915424347, 0.0009074633126147091, -0.009817041456699371, -0.021265944465994835, 0.012817604467272758, 0.0042138793505728245, 0.008234729990363121, 0.001695835031569004, 0.03009480983018875, 0.04801255464553833, 0.048210375010967255, -0.035710450261831284, 0.024411767721176147, 0.04366959258913994, -0.028004730120301247, -0.008881084620952606, -0.014628280885517597, 0.08361643552780151, -0.014546838589012623, -0.023770932108163834, 0.0073107341304421425, -0.03333678096532822, -0.05331195145845413, -0.02066359855234623, -0.041558463126420975, 0.019447259604930878, -0.019201606512069702, 0.02138744294643402, 0.02292053960263729, 0.011376447975635529, -0.029181551188230515, -0.016784409061074257, -0.00248627457767725, -0.047684863209724426, -0.007824837230145931, 0.07042431086301804, -0.036518655717372894, 0.02187480218708515, 0.011032809503376484, -0.03732702508568764, 0.04041549935936928, 0.06125478446483612, -0.023774513974785805, -0.024698428809642792, 0.03328126668930054, 0.008721892721951008, 0.013296395540237427, 0.010940203443169594, -0.02857414446771145, 0.011603822000324726, -0.016490280628204346, 0.049017563462257385, -0.03695855662226677, 0.035665638744831085, -0.02091248333454132, 0.010374167934060097, 0.018073899671435356, 0.04076731950044632, 0.010249384678900242, -0.006932951509952545, 0.013178304769098759, 0.030500726774334908, -0.023781869560480118, 0.022923998534679413, 0.015516059473156929, 0.04982244223356247, 0.03889411687850952, 0.0416928268969059, 0.02739415504038334, 0.0071804821491241455, 0.04679451137781143, 0.021840013563632965, -0.011140125803649426, 0.03564215078949928, -0.021420788019895554, -0.004743363708257675, 0.03576232120394707, 0.04442800208926201, -0.024436917155981064, 0.02608756348490715, -0.028007710352540016, -0.025138041004538536, -0.036268316209316254, 0.02224046178162098, 0.02108948305249214, 0.025470666587352753, 0.03871040791273117, 0.01086736936122179, -0.01682245172560215, 0.0210602767765522, 0.03350116312503815, 0.06531915813684464, -0.005692128092050552, -0.0059856814332306385, -0.030677352100610733, 0.015677155926823616, 0.0317133404314518, 0.02010064572095871, 0.053008291870355606, 0.007643838878720999, -0.0057911742478609085, 0.01235566008836031, -0.055790212005376816, -0.07652189582586288, -0.03582770749926567, -0.04225977510213852, -0.012948219664394855, -0.04300167039036751, -0.038529835641384125, -0.002527671167626977, 0.029900675639510155, -0.02224842831492424, -0.001700952067039907, -0.015184932388365269, -0.02591577358543873, 0.0060766031965613365, -0.01386896800249815, 0.026459619402885437, -0.01826385036110878, 0.03126632049679756, -0.03586892411112785, 0.03716657683253288, -0.03319908678531647, 0.04537452757358551, -0.021382804960012436, -0.004415787290781736, 0.006134619005024433, 0.019581574946641922, 0.04254361614584923, 0.0059051490388810635, -0.029164308682084084, -0.022568175569176674, -0.022875305265188217, -0.06647871434688568, 0.022639112547039986, -0.0113392174243927, -0.014716237783432007, 0.012011069804430008, -0.0172160305082798, 0.0434841550886631, 0.03488685563206673, -0.01645171083509922, 0.031356435269117355, 0.023803835734725, -0.05105474218726158, 0.025596443563699722, -0.005357310175895691, 0.01876199059188366, -0.047838833183050156, 0.06260152906179428, 0.0211440809071064, -2.0024681361974217e-05, -0.005312437191605568, 0.02083437703549862, -0.017486901953816414, 0.0018560526659712195, 0.009527318179607391, -0.019396262243390083, -0.025708546862006187, 0.05055324360728264, 0.00716075673699379, -0.04304550215601921, 0.018376996740698814, -0.008618184365332127, 0.00033190479734912515, -0.01826566830277443, -0.03617510199546814, 0.051165368407964706, 0.03828044980764389, 0.05426185578107834, -0.03646084666252136, -0.039008382707834244, -0.02884177677333355, 0.034725796431303024, 0.04036794975399971, -0.017953302711248398, 0.009746535681188107, 0.04721890762448311, 0.01202540472149849, 0.025486785918474197, 0.0011297640157863498, -0.008161713369190693, 0.019771413877606392, 0.007591717876493931, -0.003687323071062565, -0.004959994927048683, 0.01181277446448803, -0.015729565173387527, 0.027522731572389603, 0.03859474137425423, -0.042433083057403564, 0.046922434121370316, 0.0038519178051501513, 0.012147344648838043, 0.029792310670018196, 0.013567662797868252, -0.008446097373962402, -0.010814509354531765, -0.04356779903173447, -0.06818488985300064, 0.031955428421497345, -0.01577688753604889, 0.05179140344262123, -0.058163441717624664, 0.06111203506588936, 0.011737610213458538, -0.035533878952264786, 0.0391046367585659, -0.024787291884422302, 0.024080991744995117, -0.007841079495847225, -0.01716063730418682, 0.014096200466156006, -0.025531869381666183, 0.005327623803168535, -0.017433155328035355, 0.06304162740707397, 0.07543289661407471, 0.01571950688958168, 0.054014116525650024, -0.02724122256040573, -0.050427768379449844, -0.02549748495221138, 0.0015442747389897704, 0.004260028712451458, -0.035203658044338226, 0.05002293363213539, -0.023227551952004433, -0.08523961901664734, -0.0465489998459816, 0.029208986088633537, 0.03454216197133064, 0.02241295762360096, -0.029873501509428024, 0.00015726308629382402, -0.005502286832779646, -0.014290652237832546, 0.034294720739126205, -0.0019598742946982384, 0.038172103464603424, -0.016469940543174744, 0.045612040907144547, -0.00666686100885272, -0.015410522930324078, -0.01791660115122795, -0.012537559494376183, -0.053635917603969574, 0.0453588105738163, -0.0029234918765723705, -0.009041969664394855, -0.012383061461150646, 0.011324063874781132, 0.03547552227973938, 0.02181280218064785, -0.019498148933053017, 0.011525538749992847, -0.012559996917843819, 0.02860092744231224, 0.005268723703920841, -0.07287371158599854, -0.01464419811964035, -0.0354132242500782, 0.05065648630261421, 0.04908342286944389, 0.011445136740803719, -0.03525003045797348, 0.00430272938683629, -0.031497396528720856, -0.0645153746008873, 0.010592910461127758, 0.05078413337469101, -0.02562553621828556, 0.03679646551609039, -0.05012014880776405, 0.015974821522831917, 0.00276441453024745, 0.0015346566215157509, -0.0077170622535049915, -0.012568357400596142, 0.028139842674136162, 0.0323764868080616, 0.024113377556204796, -0.0008314937585964799, -0.016307150945067406, -0.01156257838010788, -0.07263292372226715, 0.0011903343256562948, 0.02266848087310791, -0.03263675794005394, 0.03516516834497452, 0.030683083459734917, 0.01946829818189144, 0.0435185581445694, -0.01727808080613613, 0.07233164459466934, -0.05512724071741104, 0.036221180111169815, -0.023955469951033592, -0.04078449308872223, 0.051093947142362595, 0.026091711595654488, -0.022817695513367653, 0.050516702234745026, 0.0011860346421599388, 0.0019683160353451967, -0.009243431501090527, 0.049235936254262924, -0.0470174178481102, 0.04077018052339554, -0.040767453610897064, 0.0051933773793280125, 0.016194460913538933, -0.035089172422885895, 0.015681913122534752, -0.03688392415642738, 0.026260720565915108, 0.014252346940338612, 0.02244764193892479, -0.04101819545030594, -0.034034423530101776, -0.023256046697497368, -0.037091322243213654, 0.0033504993189126253, -0.0058056931011378765, 0.020454689860343933, 0.015604528598487377, -0.022060319781303406, -0.020030658692121506, -0.018010569736361504, 0.0007797750877216458, 0.007693904917687178, 0.02321474999189377, -0.013181624002754688, 0.029439959675073624, -0.009283574298024178, -0.01701640523970127, -0.021441560238599777, -0.004634247627109289, 0.015105959959328175, -0.027900248765945435, -0.04936208575963974, 0.004174375906586647, -0.03569092974066734, -0.007284390274435282, -0.03441615775227547, 0.0171204824000597, -0.05422945320606232, 0.06041432172060013, 0.0069463131949305534, 0.0411558598279953, -0.0033390820026397705, -0.006697501055896282, -0.024914389476180077, 0.04574881121516228, 0.010451887734234333, -0.029245223850011826, -0.02555392123758793, 0.0348367877304554, -0.021192556247115135, 0.03171221911907196, -0.010004832409322262, -0.016670292243361473, -0.09865675121545792, -0.030303392559289932, 0.011668228544294834, -0.038203127682209015, 0.0028980113565921783, -0.03496034815907478, -0.032910093665122986, -0.020274197682738304, 0.017710406333208084, 0.002595791593194008, 0.004258854314684868, -0.004389781504869461, -0.011577245779335499, -0.02874322608113289, -0.0007525589899159968, -0.03422609344124794, -0.028095170855522156, 0.005800566170364618, -0.005880630109459162, 0.06386711448431015, -0.006240864284336567, 0.04142501950263977, 0.001961540197953582, 0.030961986631155014, 0.024950897321105003, -0.010406777262687683, -0.05980537459254265, -0.01057790033519268, 0.009262622334063053, -0.004312954843044281, -0.02315055951476097, 0.02365650236606598, -0.054919201880693436, 0.011977684684097767, -0.0437474399805069, 0.010738398879766464, -0.008227531798183918, -0.024477191269397736, 0.002058612182736397, 0.008173737674951553, 0.06306764483451843, -0.032219238579273224, -0.02305232733488083, 0.002410921733826399, 0.04274039342999458, 0.0897863581776619, 0.0028557186014950275, -0.03453759849071503, -0.030182495713233948, -0.013518190942704678, -0.047120679169893265, 0.04077887162566185, -0.06109820306301117, -0.023814618587493896, -0.050725508481264114, 0.004147750791162252, 0.05331015959382057, -0.005132060497999191, 0.02387206442654133, 0.05782979354262352, -0.008879812434315681, -0.006859893910586834, -0.013202748261392117, 0.008315210230648518, 0.052713263779878616, -0.05233215168118477, 0.009968122467398643, 0.0006131050758995116, -0.03698724880814552, -0.004852973390370607, -0.05060683190822601, -0.05983230099081993, -0.06022332236170769, 0.030841033905744553, 0.08705291897058487, -0.04687225818634033, 0.03702192381024361, -0.011082918383181095, -0.0609256736934185, -0.046600837260484695, 0.03814627602696419, -0.0022243508137762547, 0.015714000910520554, 0.03299833461642265, -0.0014865935081616044, -0.05084230378270149, -0.03847359120845795, 0.029044058173894882, 0.009926743805408478, -0.023801175877451897, 0.04800756275653839, -0.0014094962971284986, -0.04117937386035919, 0.042356930673122406, 0.024763554334640503, -0.05951748415827751, -0.04960503429174423, -0.01772334799170494, 0.011049673892557621, 0.022265447303652763, -0.03712579980492592, 0.0007927537662908435, -0.034506626427173615, 0.01313430443406105, 0.009239297360181808, 0.03983595594763756, -0.028114022687077522, 0.029821764677762985, 0.046966005116701126, 0.0107656791806221, -0.05601649731397629, 0.015335945412516594, -0.025011684745550156, 0.022551970556378365, -0.0518459714949131, -0.03197074681520462, -0.03387906774878502, 0.0016889016842469573, -0.012036150321364403, 0.030316686257719994, -0.010381733067333698, 0.005567480344325304, 0.020053789019584656, -0.011086585931479931, 0.07029970735311508, 0.013899111188948154, -0.017137326300144196, -0.0017857452621683478, -0.02032710798084736, -0.05856867507100105, -0.037857845425605774, 0.0037797323893755674, 0.019799143075942993, 0.010910341516137123, -0.0582394115626812, 0.00828986894339323, 0.018351277336478233, -0.017176002264022827, 0.003597338916733861, -0.04992558807134628, -0.014108051545917988, -0.05257932469248772, -0.022051796317100525, -0.003697747830301523, -0.0008083399152383208, -0.021884415298700333, 0.027355652302503586, 0.001608899561688304, -0.029270872473716736, 0.00803724117577076, -0.012339362874627113, 0.006758160423487425, 0.005729360040277243, -0.0579100139439106, 0.03913363814353943, -0.016636686399579048, -0.04358697682619095, -0.02941569872200489, 0.025984136387705803, 0.015434686094522476, 0.0012913236860185862, -0.0316198505461216, 0.008551962673664093, -0.012817501090466976, 0.017244962975382805, -0.017946697771549225, 0.0075566391460597515, -0.017268847674131393, -0.013014265336096287, -0.002560192020609975, 0.030922340229153633, -0.008224988356232643, 0.05268019437789917, 0.003982068505138159, -0.010345794260501862, 0.033131081610918045, -0.0007086062687449157, -0.053183212876319885, 0.009540816769003868, 0.0024098914582282305, -0.02192230336368084, 0.03489076718688011, -0.02789459004998207, -0.030460786074399948, -0.043980296701192856, -0.049792107194662094, 0.028000403195619583, 0.01561665441840887, 0.008705420419573784, -0.030512064695358276, 0.023569263517856598, 0.009336842224001884, 0.04857616871595383, -0.01595386676490307, 0.02648543380200863, 0.017986230552196503, 0.006866452284157276, 0.009853449650108814, -0.025783957913517952, 0.028726406395435333, 0.03419651836156845, 0.020164841786026955, -0.046281181275844574, 0.001659324741922319, -0.03997606411576271, 0.020715588703751564, 0.03762338310480118, -0.025160690769553185, -0.02623177319765091, -0.050059087574481964, -0.035821810364723206, -0.0035403678193688393, 0.049556221812963486, 0.009503236040472984, -0.021995779126882553, 0.021978596225380898, -0.04644385352730751, -0.040550705045461655, 0.00851358100771904, -0.06697086244821548, 0.021348588168621063, 0.01528340857475996, 0.008236587047576904, -0.006347618065774441, -0.05902015045285225, -0.04722190648317337, 0.0062291971407830715, -0.019358281046152115, 0.013838451355695724, -0.0035466733388602734, 0.03502141684293747, -0.033088114112615585, 0.08082045614719391, -0.017953574657440186, -0.0033512453082948923, -0.0018916953122243285, 0.08003555983304977, -0.043224409222602844, 0.011126110330224037, -0.0014269870007410645, -0.0036793588660657406, 0.010767855681478977, -0.015071810223162174, 0.014763936400413513, 0.012500972487032413, 0.01468660682439804, 0.02249286323785782, -0.02419758215546608, 0.01778545044362545, -0.021458875387907028, 0.0175654087215662, 0.03144126757979393, -0.02325422316789627, -0.02611822821199894, 0.021155884489417076, 0.009579568170011044, 0.0013043694198131561, -0.07001358270645142, 0.033840764313936234, 0.039878711104393005, -0.007659215480089188, 0.050107065588235855, 0.02813653275370598, 0.06265097111463547, -0.016166895627975464, 0.014350788667798042, 0.009526500478386879, 0.04662127420306206, -0.010926062241196632, 0.021460482850670815, 0.015947097912430763, 0.012952819466590881, 0.031770188361406326, 0.0013197602238506079, -0.011859921738505363, 0.04229843243956566, 0.03402966633439064, -0.025654928758740425, -0.002025658031925559, 0.01061029452830553, 0.016096753999590874, -0.008174530230462551, 0.014449568465352058, -0.006015534978359938, 0.0039434004575014114, 0.006568399257957935, -0.0038125556893646717, 0.019119814038276672, 0.06984272599220276, -0.018593525514006615, -0.008790146559476852, -0.00018095348787028342, -0.025544114410877228, 0.03247366100549698, 0.0587841235101223, -0.00012888140918221325, 0.009333943016827106, 0.01293751411139965, 0.018684662878513336, -0.03726072981953621, 0.03305857628583908, 0.05203338712453842, -0.0010003657080233097, -0.027955666184425354, 0.0031926827505230904, 0.024860210716724396, -0.02947157248854637, -0.0427226647734642, -0.012206871062517166, -0.035350535064935684, 0.03083735704421997, -0.01065860129892826, -0.002102561527863145, 0.06250826269388199, -0.05243202671408653, -0.013654329814016819, -0.08047977834939957, 0.03372148051857948, -0.04058969393372536, 0.011458136141300201, 0.035233329981565475, 0.010580700822174549, -0.017640111967921257, -0.0037287729792296886, 0.01675143837928772, 0.042261023074388504, -0.01691362075507641, 0.014255553483963013, -0.05057903751730919, 0.028961503878235817, 0.011759067885577679, -0.027686186134815216, -0.032204411923885345, 0.034516409039497375, -0.0052967374213039875, -0.045915938913822174, -0.004560516681522131, -0.04469607397913933, -5.723511640098877e-05, -0.021578742191195488, -0.030068790540099144, 0.0028951517306268215, 0.03491724282503128, -0.01973828487098217, -0.05615050345659256, -0.010857718996703625, 0.009235871955752373, -0.07282894104719162, 0.012966232374310493, 0.004844010807573795, 0.030470198020339012, 0.013036316260695457, -0.0070401630364358425, -0.05429765209555626, -0.031917840242385864, -0.014532040804624557, -0.009927047416567802, 0.05188415199518204, -0.012942470610141754, -1.943316965480335e-05, -0.028560632839798927, -0.035566527396440506, -0.039553623646497726, -0.03119312785565853, 0.0039594536647200584, -0.03935719653964043, 0.0461106076836586, 0.056215181946754456, -0.0005066833691671491, -0.014445992186665535, -0.0038716914132237434, -0.011317883618175983, -0.01068265363574028, 0.041

[]

In [ ]:
def get_search_result(query,collection):

  get_knowledge=vector_search(query,collection)

  search_result=""

  for result in get_knowledge:
        search_result += f"Title: {result.get('title', 'N/A')}, Plot: {result.get('fullplot', 'N/A')}\n"

  return search_result

In [ ]:
query="what is the best comedy movie to watch and why?"

In [ ]:
collection

Collection(Database(MongoClient(host=['ac-mc5oagt-shard-00-02.rus2ded.mongodb.net:27017', 'ac-mc5oagt-shard-00-00.rus2ded.mongodb.net:27017', 'ac-mc5oagt-shard-00-01.rus2ded.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', appname='Cluster0', authsource='admin', replicaset='atlas-gu114m-shard-0', tls=True, server_api=<pymongo.server_api.ServerApi object at 0x0000024BE61B1C90>), 'mongorag'), 'mongoragcollection')

In [ ]:
source_information=get_search_result(query,collection)
source_information

[0.01965291239321232, -0.023518940433859825, -0.031458478420972824, 0.014970564283430576, -0.016353173181414604, -0.016895772889256477, -0.01193644292652607, 0.04158833995461464, -0.013356583192944527, 0.044313643127679825, 0.004574717953801155, 0.010549059137701988, 0.012763175182044506, -0.04828539863228798, 0.005650641396641731, -0.031372006982564926, -0.03754856064915657, -0.03725145384669304, -0.029740240424871445, 0.01936694234609604, 0.004532249644398689, 0.016592107713222504, -0.03431978449225426, -0.009278467856347561, 0.008219541050493717, 0.020317675545811653, -0.009512979537248611, 0.0006079958402551711, 0.05204164236783981, 0.07381503283977509, 0.01297515444457531, -0.05585036054253578, 0.018980052322149277, -0.060788922011852264, 0.011161549016833305, -0.03324291855096817, 0.02635188400745392, 0.018502064049243927, -0.011724855750799179, -0.04501267522573471, -0.036180201917886734, -0.021296026185154915, 0.03862366825342178, -0.027672817930579185, -0.055619414895772934, 0.0015896649565547705, 0.013469500467181206, -0.023891791701316833, -0.0080284858122468, -0.021855998784303665, 0.012061362154781818, -0.03043905831873417, 0.028970560058951378, -0.004976504947990179, 0.015641329810023308, 0.012714816257357597, 0.0034399786964058876, -0.005221971310675144, 0.0032205248717218637, 0.012574663385748863, 0.029523365199565887, -0.010914118029177189, 0.005073989275842905, -0.021816279739141464, 0.051451411098241806, 0.015651557594537735, 0.021105052903294563, 0.003231313545256853, 0.05367721989750862, 0.024140572175383568, 0.007217494770884514, 4.443816214916296e-05, 0.0031975717283785343, -0.03790163993835449, 0.005645914934575558, 0.0026102098636329174, -0.01091769989579916, 0.03888320177793503, -0.04285435751080513, -0.004506743047386408, 0.029439061880111694, 0.06971578299999237, 0.01553430501371622, 0.01737624779343605, -0.067678302526474, -0.047868456691503525, 0.020643409341573715, 0.049927424639463425, -0.018454095348715782, 0.02012050151824951, 0.018359217792749405, 0.017228620126843452, -0.0018875225214287639, -0.015592225827276707, 0.04105374217033386, 0.025188928470015526, -0.04915190860629082, 0.019214404746890068, 0.014499715529382229, 0.004482985939830542, 0.006578925531357527, 0.03571531921625137, -0.033317938446998596, 0.016440918669104576, -0.02481314353644848, 0.009943580254912376, 0.023818571120500565, 0.004099101759493351, -0.03049335815012455, -0.03067854978144169, -0.0017086508451029658, 0.004323219880461693, 0.011222278699278831, 0.01129341870546341, -0.032051682472229004, 0.012601715512573719, 0.004447932820767164, 0.0864156112074852, -0.04101618006825447, 0.011941507458686829, 0.005958066321909428, 0.02731427736580372, 0.052955031394958496, -0.025111597031354904, 0.039773568511009216, -0.02786225453019142, -0.021494751796126366, 0.030898960307240486, -0.014647483825683594, -0.0027465361636132, 0.01222701370716095, -0.025909435003995895, -0.006179910618811846, 0.045283105224370956, -0.027666723355650902, 0.008950826711952686, -0.02124866098165512, 0.021917346864938736, 0.017714038491249084, -0.041261445730924606, 0.05553284287452698, 0.03435434028506279, -0.011632904410362244, 0.08307056874036789, 0.014463551342487335, 0.008471173234283924, 0.0012282681418582797, -0.02636689320206642, 0.013989055529236794, 0.035395510494709015, -0.021095992997288704, 0.020147275179624557, 0.007124986499547958, 0.008470048196613789, -0.01913991943001747, -0.012122957967221737, -0.01350927259773016, 0.012558595277369022, 0.05597946047782898, 0.057051923125982285, 0.01642891764640808, 0.001156700192950666, -0.042080141603946686, 0.07136178016662598, -0.0015140947652980685, 0.04798094555735588, -0.03692646697163582, 0.00018264702521264553, -0.025756094604730606, -0.005409345030784607, 0.009814160875976086, -0.0022446357179433107, -0.012116576544940472, 0.0077186026610434055, 0.0224155280739069, 0.05255955085158348, 0.04733223468065262, -0.05484498292207718, 0.03100571222603321, 0.012171939946711063, -0.0326463021337986, -0.009379354305565357, -0.04714255407452583, 0.05981780216097832, -0.02011134661734104, -0.013046154752373695, -0.0004904738743789494, -0.038947056978940964, -0.06301939487457275, -0.028575412929058075, -0.03897882252931595, -0.018349768593907356, -0.0185434240847826, 0.03547682985663414, 0.02216642163693905, 0.018294397741556168, -0.019528383389115334, -0.015670837834477425, -0.01152963936328888, -0.05598399415612221, -0.02085619792342186, 0.06371618062257767, -0.024000685662031174, -0.0008613561512902379, -0.006751753855496645, -0.03976324573159218, 0.02631986141204834, 0.08376984298229218, -0.060333944857120514, -0.01345786266028881, 0.03172682970762253, 0.035597119480371475, -0.012081324122846127, -0.016489708796143532, -0.0021425969898700714, 0.001574282068759203, -0.0064196097664535046, 0.0367606095969677, -0.02076917327940464, 0.029315892606973648, 0.003526214277371764, 0.004388941917568445, 0.024949442595243454, 0.03183886408805847, 0.006414380855858326, -0.009478433057665825, -0.01351906731724739, 0.012979009188711643, -0.04202231764793396, 0.010102690197527409, -0.011807898990809917, 0.04815836250782013, 0.016571054235100746, 0.050070587545633316, 0.03429318219423294, 0.00648987153545022, 0.07603219896554947, 0.03424600511789322, -0.002856773789972067, 0.03701217100024223, -0.01869589276611805, 0.013456825166940689, 0.03236101567745209, 0.03598388656973839, -0.012135382741689682, 0.010214474983513355, 0.013030427508056164, 0.002536879386752844, 0.0018113397527486086, 0.03803500160574913, 0.024195201694965363, 0.026604298502206802, 0.0283947940915823, 0.0455508753657341, -0.00607934407889843, 0.041441746056079865, 0.052749115973711014, 0.07711972296237946, -0.0026388242840766907, -0.005486801732331514, -0.03380320221185684, 0.025384435430169106, 0.03239983692765236, -0.0029367918614298105, 0.02635803632438183, -0.023512251675128937, -0.037379492074251175, 0.0602276436984539, -0.051081333309412, -0.06496936082839966, -0.02343282662332058, -0.04960617050528526, -0.02071290649473667, -0.07872065901756287, -0.03628477826714516, -0.009833880700170994, 0.02565491572022438, -0.028743963688611984, 0.02301650680601597, -0.013868464156985283, -0.016503702849149704, -0.006496545393019915, -0.013872204348444939, 0.04242008924484253, 0.014983238652348518, 0.04023012891411781, -0.010666179470717907, 0.02906637266278267, -0.006343015935271978, 0.048463091254234314, -0.035528164356946945, -0.011314835399389267, -0.02442372776567936, 0.04037121683359146, 0.01198215875774622, -0.00526219280436635, -0.020351538434624672, 0.00977716501802206, -0.028345387428998947, -0.059640802443027496, 0.022583022713661194, -0.00917342584580183, 0.003850839100778103, 0.02629702165722847, -0.027851734310388565, 0.04749339073896408, 0.03860051929950714, -0.027068404480814934, 0.053913094103336334, 0.03818119689822197, -0.04878845438361168, 0.05156567692756653, 0.005631709471344948, 0.01906559430062771, -0.051691167056560516, 0.03467274457216263, 0.01730222813785076, 0.0411701463162899, -0.04317816346883774, -0.011254151351749897, -0.029166152700781822, -0.005785635206848383, 0.018626824021339417, 0.019623372703790665, -0.0550650916993618, 0.05243654549121857, 0.013709861785173416, -0.03372325748205185, 0.046833477914333344, -0.031107045710086823, -0.010254994966089725, -0.02760782651603222, -0.06874608248472214, 0.033255741000175476, 0.03470893204212189, 0.03051259182393551, -0.0083707170560956, -0.026688477024435997, -0.008031753823161125, 0.048097677528858185, 0.024708954617381096, 0.002556034130975604, 0.02694319188594818, 0.028468435630202293, 0.01647893525660038, 0.053543541580438614, 0.010187588632106781, -0.01703747548162937, 0.017878104001283646, 0.02211824059486389, -0.004897747654467821, 0.006482240278273821, 0.029469791799783707, 0.01199747622013092, 0.021581754088401794, 0.014019514434039593, -0.03484230488538742, 0.026687074452638626, 0.01369050145149231, 0.007594570517539978, 0.008320413529872894, 0.023899994790554047, 0.021294863894581795, -0.002658049575984478, -0.020322976633906364, -0.05366457253694534, 0.013301042839884758, -0.01118836086243391, 0.02599242515861988, -0.09751635789871216, 0.03644881024956703, -0.01008728425949812, -0.04272385314106941, 0.03520449623465538, -0.009979032911360264, 0.016671760007739067, -0.001226465916261077, -0.01077257376164198, -0.0165981724858284, -0.04533272609114647, 0.010255290195345879, -0.049678001552820206, 0.05029575154185295, 0.043289583176374435, -0.009375563822686672, 0.027745189145207405, -0.028346488252282143, -0.022675897926092148, -0.047166723757982254, -0.03392711281776428, -0.01275866013020277, -0.010905121453106403, 0.03048768639564514, -0.0014811770524829626, -0.060441963374614716, -0.04265865311026573, 0.028211597353219986, 0.03410119563341141, 0.021103864535689354, -0.008475841023027897, 0.002374280011281371, -0.008141704834997654, 0.0014563703443855047, 0.01869458332657814, 0.02550928294658661, 0.02259700931608677, -0.028944242745637894, 0.037097666412591934, -0.013477960601449013, -0.011205239221453667, -0.025490816682577133, -0.010316691361367702, -0.031705256551504135, 0.0635499358177185, 0.010386954993009567, 0.0088915154337883, -0.02760835736989975, 0.023588983342051506, -0.014563736505806446, 0.008668019436299801, -0.0012636266183108091, -0.0021958942525088787, -0.007556270807981491, -0.0004969454603269696, 0.015710001811385155, -0.03809475153684616, -0.026911912485957146, -0.015007997862994671, 0.052534300833940506, 0.04221852496266365, -0.0042799548245966434, -0.027775689959526062, -0.01478387601673603, -0.030034327879548073, -0.03268101066350937, 0.00954934861510992, 0.05119048431515694, 0.004518677480518818, 0.030267639085650444, -0.0456906333565712, 0.02657618187367916, 0.00742961373180151, 0.022585464641451836, 0.0073815276846289635, 0.0015914823161438107, 0.03334616497159004, 0.022152144461870193, 0.020276153460144997, -0.028409922495484352, -0.037561625242233276, -0.022178160026669502, -0.07050210237503052, 0.017062854021787643, 0.018561456352472305, -0.04387504234910011, 0.014406400732696056, 0.0365867055952549, 0.017089802771806717, 0.03546172380447388, -0.011127002537250519, 0.045940984040498734, -0.02867520973086357, 0.03080003708600998, -0.035556674003601074, -0.046171680092811584, 0.028022829443216324, 0.008624454960227013, -0.0040961867198348045, 0.030679229646921158, 0.049148786813020706, -0.01433711126446724, -0.013855957426130772, 0.03518218174576759, -0.04985308274626732, 0.03920488432049751, -0.03619774803519249, 0.015143320895731449, -0.025681147351861, -0.026880016550421715, -0.007906384766101837, -0.043997280299663544, 0.03714398294687271, 0.01866929605603218, 0.031558189541101456, -0.030545637011528015, -0.06006056070327759, -0.010621240362524986, -0.006024238653481007, -0.013136878609657288, 0.00014717975864186883, 0.0009931728709489107, 0.005430135875940323, -0.01485962513834238, -0.02744484692811966, -0.021629827097058296, -0.02175918221473694, -0.005229071248322725, 0.018585205078125, -0.045827481895685196, 0.02233831398189068, 0.0013951585860922933, -0.0007818929152563214, -0.003044365206733346, -0.0016069950070232153, 0.002488700905814767, -0.0221576951444149, -0.03731232136487961, 0.023619776591658592, -0.03264955058693886, 0.016839327290654182, -0.036219291388988495, 0.03464502468705177, -0.03142869099974632, 0.06882594525814056, 0.027647996321320534, 0.017973504960536957, 0.01152582373470068, -0.008741320110857487, -0.04666256532073021, 0.03748222440481186, -0.005973661318421364, -0.031795114278793335, -0.02812303975224495, 0.05033862218260765, -0.03673964738845825, 0.0386512391269207, 0.003989907447248697, -0.017058007419109344, -0.07303254306316376, -0.04228183627128601, -0.002971615409478545, -0.04134899377822876, -0.02739175595343113, -0.03552623838186264, -0.002687389263883233, -0.016532626003026962, 0.04982706904411316, 0.003626785008236766, 0.008621050976216793, -0.014543934725224972, -0.019081737846136093, -0.018157320097088814, -0.019952908158302307, -0.03501307591795921, -0.032341498881578445, 0.008753975853323936, 0.0036092011723667383, 0.03284928575158119, 0.0009745474089868367, 0.05379878357052803, 0.007925691083073616, 0.03513055294752121, 0.024958616122603416, -0.0330706387758255, -0.03721397742629051, -0.021386221051216125, -8.554270607419312e-05, -0.019190588966012, -0.006677465047687292, 0.021721087396144867, -0.06774336844682693, 0.024076497182250023, -0.04531148076057434, 0.026122739538550377, -0.023481978103518486, -0.010707361623644829, -0.011986522004008293, -0.016845205798745155, 0.06583359092473984, -0.015719708055257797, -0.02503322809934616, -0.026406174525618553, 0.04164450243115425, 0.07102768123149872, 0.00026901837554760277, -0.041866373270750046, -0.004879737738519907, -0.028467463329434395, -0.0536610446870327, 0.029634367674589157, -0.029216177761554718, -0.03360432758927345, -0.08063098043203354, 0.009388393722474575, 0.023360779508948326, 0.004741499666124582, 0.011251204647123814, 0.048731233924627304, -0.007942147552967072, -0.03200230374932289, -0.011305122636258602, 0.018218569457530975, 0.04168763384222984, -0.021117042750120163, -0.014673271216452122, -0.02217603102326393, -0.010969393886625767, -0.008731679059565067, -0.05005122721195221, -0.05406281352043152, -0.0590127632021904, -0.004750480875372887, 0.08054939657449722, -0.03510825335979462, 0.04593940079212189, 0.006256721448153257, -0.07309125363826752, -0.050394363701343536, 0.03610169515013695, -0.01115887425839901, 0.0012397918617352843, 0.058112092316150665, -0.016345834359526634, -0.03988766670227051, -0.01557045616209507, 0.04718451574444771, -0.038628268986940384, -0.018653500825166702, 0.06418310105800629, -0.021269164979457855, -0.0445934422314167, 0.045910075306892395, 0.04812103882431984, -0.04470270127058029, -0.06678023189306259, 0.0046835909597575665, -0.001960071502253413, 0.025917192921042442, -0.033127643167972565, -0.012833832763135433, -0.029298488050699234, 0.005405114032328129, 0.02953144907951355, 0.025470826774835587, -0.02360636554658413, 0.023296913132071495, 0.02654450573027134, 0.012263327836990356, -0.05111398547887802, 0.03290746733546257, 0.015007507055997849, -0.006525745615363121, -0.029829060658812523, -0.02608613856136799, 0.029950225725769997, -0.016499757766723633, -0.03318341448903084, 0.03133387863636017, -0.015401892364025116, -0.007466910872608423, 0.027431515976786613, -0.010099445469677448, 0.019009962677955627, 0.013276204466819763, 0.0001867475511971861, -0.031981419771909714, -0.02968808077275753, -0.04154590144753456, -0.05084166303277016, 0.008496062830090523, -0.019067352637648582, 0.016969243064522743, -0.04674485698342323, 0.0008716860320419073, 0.008192870765924454, -0.017143147066235542, 0.0004220478585921228, -0.047505803406238556, -0.02581046335399151, -0.044247400015592575, -0.02685241587460041, -0.01956132985651493, 0.025183629244565964, 0.02828124351799488, 0.049957625567913055, 0.03223085403442383, -0.02798398584127426, -0.017311304807662964, -0.005535896401852369, -0.014808019623160362, -0.016499849036335945, -0.05544670298695564, 0.01678372360765934, -0.005441462155431509, -0.03821539133787155, -0.03738807514309883, 0.01894240640103817, -0.020603369921445847, -0.02014102227985859, -0.01861715503036976, 0.001795078394934535, -0.00499058049172163, 0.025163765996694565, -0.005500369239598513, -0.018074195832014084, 0.009039314463734627, -0.03099687211215496, -0.00405803183093667, 0.032848816365003586, -0.002014249563217163, 0.06517544388771057, -0.007060937583446503, -0.0306033156812191, 0.026861894875764847, -0.020858701318502426, -0.02836814895272255, -0.003655798966065049, 0.004823727533221245, -0.024801811203360558, 0.0522129200398922, -0.02800557389855385, -0.03619517758488655, -0.044227831065654755, -0.02449686825275421, 0.04025697708129883, 0.010255877859890461, 0.009651687927544117, -0.036710526794195175, 0.021477844566106796, 0.009176329709589481, 0.06106403097510338, -0.0059060826897621155, 0.033983077853918076, 0.044571638107299805, -0.008645028807222843, -0.004125160165131092, -0.019505448639392853, 0.021310532465577126, 0.021790923550724983, 0.032408133149147034, -0.03050898015499115, -0.004505224991589785, -0.011115459725260735, -0.010632991790771484, 0.048079244792461395, -0.017596451565623283, -0.009736863896250725, -0.03814234212040901, -0.009104837663471699, -0.011082674376666546, 0.05373416095972061, 0.027381813153624535, -0.041469961404800415, 0.039341866970062256, -0.043223682790994644, -0.06079202517867088, -0.016224998980760574, -0.08323096483945847, 0.010590904392302036, 0.040223702788352966, -0.020878754556179047, -0.009814460761845112, -0.05085701122879982, -0.04898511990904808, 0.018502123653888702, 0.01871655136346817, 0.005758453160524368, -0.034012794494628906, 0.030273543670773506, -0.022629810497164726, 0.056126974523067474, -0.008383107371628284, -0.011747785843908787, -0.003795660100877285, 0.06678573787212372, -0.02694562077522278, -0.00818085577338934, 0.012700905092060566, -0.005457768216729164, 0.0002677098091226071, 0.0018230926943942904, 0.014762240462005138, 0.035853635519742966, 0.024441294372081757, 0.02074410952627659, -0.0037328375037759542, 0.03290432691574097, 0.018806826323270798, 0.033511996269226074, 0.038564473390579224, -0.017125805839896202, -0.029317909851670265, 0.032610077410936356, 0.011893536895513535, 0.009067423641681671, -0.06395984441041946, 0.04160451889038086, 0.017432479187846184, -0.028673794120550156, 0.053233277052640915, 0.037784598767757416, 0.040195293724536896, -0.017953604459762573, 0.021605292335152626, -0.014976137317717075, 0.030716916546225548, 0.014284965582191944, 0.02484460175037384, 0.009087467566132545, 0.01177617534995079, 0.04015141725540161, -0.009556902572512627, -0.003945125732570887, 0.021481575444340706, 0.02880200557410717, -0.011697662994265556, 0.0019170161103829741, 0.026993324980139732, 0.034907132387161255, 0.0020179692655801773, -0.01005813293159008, -0.00425776606425643, -0.0063421763479709625, -0.0027330697048455477, -0.014437037520110607, 0.01712137646973133, 0.04194642975926399, -0.029637716710567474, -0.006053666118532419, -0.005778367631137371, -0.030193757265806198, -0.00018423280562274158, 0.07146893441677094, 0.009211620315909386, 0.0017627538181841373, 0.0047650872729718685, -0.0283450186252594, -0.017470436170697212, 0.032901830971241, 0.03654501214623451, -0.0025384430773556232, -0.05031962692737579, -0.00105666508898139, 0.03499040752649307, -0.01866121217608452, -0.03140264376997948, 0.005560087040066719, -0.05520277097821236, 0.0547388456761837, 0.0028516079764813185, 0.005663788411766291, 0.031636182218790054, -0.06861421465873718, -0.02976445108652115, -0.06585526466369629, 0.05408826842904091, -0.036492835730314255, -0.005394130013883114, 0.03726767748594284, -0.015141690149903297, -0.022531749680638313, 0.017692752182483673, 0.0038533976767212152, 0.055576618760824203, -0.0047649601474404335, 0.05570976808667183, -0.026927441358566284, 0.025162942707538605, 0.0426335409283638, -0.013755189254879951, -0.0021161665208637714, 0.016766944900155067, -0.0026725097559392452, -0.01895993761718273, 0.007718496955931187, -0.07314810901880264, -0.01926044002175331, -0.024402491748332977, -0.0374593548476696, -0.01794382557272911, 0.029695190489292145, -0.02384456992149353, -0.05309097841382027, -0.02727501280605793, 0.038000911474227905, -0.06059005856513977, 0.03180979564785957, 0.017977958545088768, 0.04968498274683952, -0.03664778918027878, -0.0011943575227633119, -0.057350970804691315, -0.03855341672897339, 0.011088849976658821, -0.019978774711489677, 0.029186541214585304, -0.029709499329328537, 0.0073544979095458984, -0.0601753331720829, -0.024827737361192703, -0.03824660927057266, -0.01578962430357933, -0.03921588137745857, -0.05047737807035446, 0.07291781902313232, 0.043125174939632416, 0.0015453154919669032, -0.010022838599979877, -0.013980194926261902, -0.011035282164812088, -0.00457038264721632, 0.053614139556884766, -0.00787714123725891

''

In [ ]:
combined_information = f"Query: {query}\nContinue to answer the query by using the Search Results:\n{source_information}."

print(combined_information)

Query: what is the best comedy movie to watch and why?
Continue to answer the query by using the Search Results:
.

In [ ]:
def get_embedding(text:str)->list[float]:

  if not text.strip():
    print("attempted to get embedding for empty text.")
    return []

  embedding=embedding_model.encode(text)
  return embedding.tolist()

In [ ]:
def vector_search(user_query,collection):

  query_embedding=get_embedding(user_query)
  print(query_embedding)

  if query_embedding is None:
    return "Invalid query or embeddig is failed"

  pipeline=[

            {
                "$vectorSearch":{

                "index": "vector_index",
                "queryVector": query_embedding,
                "path": "embedding",
                "numCandidates": 150,  # Number of candidate matches to consider
                "limit": 4,  # Return top 4 matches


                }

            },

              {
                 "$project":{

                "fullplot": 1,  # Include the plot field
                "title": 1,  # Include the title field
                "genres": 1,  # Include the genres field
                "score": {"$meta": "vectorSearchScore"},  # Include the search score
                 }

            }

           ]

  result=collection.aggregate(pipeline)
  return list(result)

In [ ]:
vector_search("what is the best horror movie to watch and why?",collection)

[0.019185921177268028, -0.015472998842597008, -0.03955463692545891, 0.002369282301515341, -0.0026591995265334845, 0.005181849468499422, -0.007513169664889574, 0.04510665312409401, -0.018112152814865112, 0.042973391711711884, 0.01343401987105608, -0.0028707829769700766, 0.005479617975652218, -0.031249191612005234, -0.0040832762606441975, -0.031060393899679184, -0.04105724021792412, -0.030109740793704987, -0.03216371312737465, 0.027480358257889748, -0.0031675698701292276, 0.01684349775314331, -0.04414497688412666, -0.02399815246462822, -0.015581835061311722, 0.017874479293823242, 0.02161523886024952, -0.03042467124760151, 0.04588271304965019, 0.07223066687583923, 0.0023236689157783985, -0.04596634581685066, 0.026177139952778816, -0.048973821103572845, -0.03348345682024956, -0.010094995610415936, 0.0548892468214035, 0.0015839148545637727, -0.0027255131863057613, -0.038032565265893936, 0.01665717177093029, 0.014302357099950314, 0.04556028172373772, -0.011216177605092525, -0.05046369507908821, 0.0023861045483499765, 0.017925534397363663, -0.030081860721111298, -0.007713163737207651, -0.021677710115909576, 0.0025280362460762262, -0.03760185092687607, 0.011060122400522232, 0.006693254690617323, 0.013570711016654968, 0.02686602994799614, -0.011295484378933907, -0.013143062591552734, 0.00019356614211574197, 0.04410506412386894, 0.021538356319069862, -0.021799027919769287, 0.024568935856223106, -0.0283063892275095, 0.015344264917075634, 0.024441977962851524, 0.010560423135757446, -0.030671698972582817, 0.028781559318304062, 0.033182621002197266, 0.01933882012963295, -0.0029937559738755226, -0.019163787364959717, 0.01936383917927742, 0.01144575234502554, 0.02072315104305744, -0.01135884877294302, 0.027792207896709442, -0.015587683767080307, -0.020335961133241653, 0.01052192971110344, 0.05448819324374199, 0.021207375451922417, 0.015374410897493362, -0.0703800767660141, -0.04530000314116478, -0.017124861478805542, 0.02929656207561493, -0.014126786030828953, 0.0382278673350811, 0.03566664457321167, 0.027214163914322853, 0.011118213646113873, -0.032380275428295135, 0.04557011276483536, 0.05568910390138626, -0.03874795138835907, -0.005883869715034962, 0.0031911595724523067, -0.017282329499721527, 0.005285183433443308, 0.04445952922105789, -0.0044273920357227325, 0.028387324884533882, -0.03157701715826988, -0.005482749547809362, 0.02533877082169056, -0.004885320086032152, -0.024914715439081192, -0.05109068751335144, -0.007489930838346481, -0.036728985607624054, 0.00919526256620884, 0.010751624591648579, -0.011365924961864948, 0.03295490890741348, -0.004312330391258001, 0.04387517273426056, -0.059020426124334335, 0.02311747521162033, 0.01511062029749155, -0.00029512454057112336, 0.054292403161525726, -0.031850673258304596, 0.05932876095175743, -0.04194685444235802, -0.007042129524052143, 0.03700248524546623, -0.03655996173620224, -0.006839779671281576, -0.002326343907043338, -0.02935059554874897, 0.0031672262120991945, 0.04241705685853958, 0.01748664677143097, 0.015422792173922062, -0.0034261082764714956, -0.0076525029726326466, 0.024394555017352104, -0.051861438900232315, 0.042092952877283096, 0.006301604676991701, 0.008150339126586914, 0.07824896275997162, 0.007197103463113308, -0.008467086590826511, 0.018384108319878578, -0.008630882948637009, -0.008001118898391724, 0.03481711819767952, -0.0060943919233977795, 0.0023830533027648926, 0.005015701986849308, 0.018067052587866783, -0.01355196163058281, -0.023615287616848946, -0.021410604938864708, 0.020231517031788826, 0.00884122122079134, 0.06210235878825188, 0.04051230102777481, 0.022513380274176598, -0.03465414419770241, 0.038845986127853394, -0.002171834697946906, 0.04867856204509735, -0.03257758915424347, 0.0009074633126147091, -0.009817041456699371, -0.021265944465994835, 0.012817604467272758, 0.0042138793505728245, 0.008234729990363121, 0.001695835031569004, 0.03009480983018875, 0.04801255464553833, 0.048210375010967255, -0.035710450261831284, 0.024411767721176147, 0.04366959258913994, -0.028004730120301247, -0.008881084620952606, -0.014628280885517597, 0.08361643552780151, -0.014546838589012623, -0.023770932108163834, 0.0073107341304421425, -0.03333678096532822, -0.05331195145845413, -0.02066359855234623, -0.041558463126420975, 0.019447259604930878, -0.019201606512069702, 0.02138744294643402, 0.02292053960263729, 0.011376447975635529, -0.029181551188230515, -0.016784409061074257, -0.00248627457767725, -0.047684863209724426, -0.007824837230145931, 0.07042431086301804, -0.036518655717372894, 0.02187480218708515, 0.011032809503376484, -0.03732702508568764, 0.04041549935936928, 0.06125478446483612, -0.023774513974785805, -0.024698428809642792, 0.03328126668930054, 0.008721892721951008, 0.013296395540237427, 0.010940203443169594, -0.02857414446771145, 0.011603822000324726, -0.016490280628204346, 0.049017563462257385, -0.03695855662226677, 0.035665638744831085, -0.02091248333454132, 0.010374167934060097, 0.018073899671435356, 0.04076731950044632, 0.010249384678900242, -0.006932951509952545, 0.013178304769098759, 0.030500726774334908, -0.023781869560480118, 0.022923998534679413, 0.015516059473156929, 0.04982244223356247, 0.03889411687850952, 0.0416928268969059, 0.02739415504038334, 0.0071804821491241455, 0.04679451137781143, 0.021840013563632965, -0.011140125803649426, 0.03564215078949928, -0.021420788019895554, -0.004743363708257675, 0.03576232120394707, 0.04442800208926201, -0.024436917155981064, 0.02608756348490715, -0.028007710352540016, -0.025138041004538536, -0.036268316209316254, 0.02224046178162098, 0.02108948305249214, 0.025470666587352753, 0.03871040791273117, 0.01086736936122179, -0.01682245172560215, 0.0210602767765522, 0.03350116312503815, 0.06531915813684464, -0.005692128092050552, -0.0059856814332306385, -0.030677352100610733, 0.015677155926823616, 0.0317133404314518, 0.02010064572095871, 0.053008291870355606, 0.007643838878720999, -0.0057911742478609085, 0.01235566008836031, -0.055790212005376816, -0.07652189582586288, -0.03582770749926567, -0.04225977510213852, -0.012948219664394855, -0.04300167039036751, -0.038529835641384125, -0.002527671167626977, 0.029900675639510155, -0.02224842831492424, -0.001700952067039907, -0.015184932388365269, -0.02591577358543873, 0.0060766031965613365, -0.01386896800249815, 0.026459619402885437, -0.01826385036110878, 0.03126632049679756, -0.03586892411112785, 0.03716657683253288, -0.03319908678531647, 0.04537452757358551, -0.021382804960012436, -0.004415787290781736, 0.006134619005024433, 0.019581574946641922, 0.04254361614584923, 0.0059051490388810635, -0.029164308682084084, -0.022568175569176674, -0.022875305265188217, -0.06647871434688568, 0.022639112547039986, -0.0113392174243927, -0.014716237783432007, 0.012011069804430008, -0.0172160305082798, 0.0434841550886631, 0.03488685563206673, -0.01645171083509922, 0.031356435269117355, 0.023803835734725, -0.05105474218726158, 0.025596443563699722, -0.005357310175895691, 0.01876199059188366, -0.047838833183050156, 0.06260152906179428, 0.0211440809071064, -2.0024681361974217e-05, -0.005312437191605568, 0.02083437703549862, -0.017486901953816414, 0.0018560526659712195, 0.009527318179607391, -0.019396262243390083, -0.025708546862006187, 0.05055324360728264, 0.00716075673699379, -0.04304550215601921, 0.018376996740698814, -0.008618184365332127, 0.00033190479734912515, -0.01826566830277443, -0.03617510199546814, 0.051165368407964706, 0.03828044980764389, 0.05426185578107834, -0.03646084666252136, -0.039008382707834244, -0.02884177677333355, 0.034725796431303024, 0.04036794975399971, -0.017953302711248398, 0.009746535681188107, 0.04721890762448311, 0.01202540472149849, 0.025486785918474197, 0.0011297640157863498, -0.008161713369190693, 0.019771413877606392, 0.007591717876493931, -0.003687323071062565, -0.004959994927048683, 0.01181277446448803, -0.015729565173387527, 0.027522731572389603, 0.03859474137425423, -0.042433083057403564, 0.046922434121370316, 0.0038519178051501513, 0.012147344648838043, 0.029792310670018196, 0.013567662797868252, -0.008446097373962402, -0.010814509354531765, -0.04356779903173447, -0.06818488985300064, 0.031955428421497345, -0.01577688753604889, 0.05179140344262123, -0.058163441717624664, 0.06111203506588936, 0.011737610213458538, -0.035533878952264786, 0.0391046367585659, -0.024787291884422302, 0.024080991744995117, -0.007841079495847225, -0.01716063730418682, 0.014096200466156006, -0.025531869381666183, 0.005327623803168535, -0.017433155328035355, 0.06304162740707397, 0.07543289661407471, 0.01571950688958168, 0.054014116525650024, -0.02724122256040573, -0.050427768379449844, -0.02549748495221138, 0.0015442747389897704, 0.004260028712451458, -0.035203658044338226, 0.05002293363213539, -0.023227551952004433, -0.08523961901664734, -0.0465489998459816, 0.029208986088633537, 0.03454216197133064, 0.02241295762360096, -0.029873501509428024, 0.00015726308629382402, -0.005502286832779646, -0.014290652237832546, 0.034294720739126205, -0.0019598742946982384, 0.038172103464603424, -0.016469940543174744, 0.045612040907144547, -0.00666686100885272, -0.015410522930324078, -0.01791660115122795, -0.012537559494376183, -0.053635917603969574, 0.0453588105738163, -0.0029234918765723705, -0.009041969664394855, -0.012383061461150646, 0.011324063874781132, 0.03547552227973938, 0.02181280218064785, -0.019498148933053017, 0.011525538749992847, -0.012559996917843819, 0.02860092744231224, 0.005268723703920841, -0.07287371158599854, -0.01464419811964035, -0.0354132242500782, 0.05065648630261421, 0.04908342286944389, 0.011445136740803719, -0.03525003045797348, 0.00430272938683629, -0.031497396528720856, -0.0645153746008873, 0.010592910461127758, 0.05078413337469101, -0.02562553621828556, 0.03679646551609039, -0.05012014880776405, 0.015974821522831917, 0.00276441453024745, 0.0015346566215157509, -0.0077170622535049915, -0.012568357400596142, 0.028139842674136162, 0.0323764868080616, 0.024113377556204796, -0.0008314937585964799, -0.016307150945067406, -0.01156257838010788, -0.07263292372226715, 0.0011903343256562948, 0.02266848087310791, -0.03263675794005394, 0.03516516834497452, 0.030683083459734917, 0.01946829818189144, 0.0435185581445694, -0.01727808080613613, 0.07233164459466934, -0.05512724071741104, 0.036221180111169815, -0.023955469951033592, -0.04078449308872223, 0.051093947142362595, 0.026091711595654488, -0.022817695513367653, 0.050516702234745026, 0.0011860346421599388, 0.0019683160353451967, -0.009243431501090527, 0.049235936254262924, -0.0470174178481102, 0.04077018052339554, -0.040767453610897064, 0.0051933773793280125, 0.016194460913538933, -0.035089172422885895, 0.015681913122534752, -0.03688392415642738, 0.026260720565915108, 0.014252346940338612, 0.02244764193892479, -0.04101819545030594, -0.034034423530101776, -0.023256046697497368, -0.037091322243213654, 0.0033504993189126253, -0.0058056931011378765, 0.020454689860343933, 0.015604528598487377, -0.022060319781303406, -0.020030658692121506, -0.018010569736361504, 0.0007797750877216458, 0.007693904917687178, 0.02321474999189377, -0.013181624002754688, 0.029439959675073624, -0.009283574298024178, -0.01701640523970127, -0.021441560238599777, -0.004634247627109289, 0.015105959959328175, -0.027900248765945435, -0.04936208575963974, 0.004174375906586647, -0.03569092974066734, -0.007284390274435282, -0.03441615775227547, 0.0171204824000597, -0.05422945320606232, 0.06041432172060013, 0.0069463131949305534, 0.0411558598279953, -0.0033390820026397705, -0.006697501055896282, -0.024914389476180077, 0.04574881121516228, 0.010451887734234333, -0.029245223850011826, -0.02555392123758793, 0.0348367877304554, -0.021192556247115135, 0.03171221911907196, -0.010004832409322262, -0.016670292243361473, -0.09865675121545792, -0.030303392559289932, 0.011668228544294834, -0.038203127682209015, 0.0028980113565921783, -0.03496034815907478, -0.032910093665122986, -0.020274197682738304, 0.017710406333208084, 0.002595791593194008, 0.004258854314684868, -0.004389781504869461, -0.011577245779335499, -0.02874322608113289, -0.0007525589899159968, -0.03422609344124794, -0.028095170855522156, 0.005800566170364618, -0.005880630109459162, 0.06386711448431015, -0.006240864284336567, 0.04142501950263977, 0.001961540197953582, 0.030961986631155014, 0.024950897321105003, -0.010406777262687683, -0.05980537459254265, -0.01057790033519268, 0.009262622334063053, -0.004312954843044281, -0.02315055951476097, 0.02365650236606598, -0.054919201880693436, 0.011977684684097767, -0.0437474399805069, 0.010738398879766464, -0.008227531798183918, -0.024477191269397736, 0.002058612182736397, 0.008173737674951553, 0.06306764483451843, -0.032219238579273224, -0.02305232733488083, 0.002410921733826399, 0.04274039342999458, 0.0897863581776619, 0.0028557186014950275, -0.03453759849071503, -0.030182495713233948, -0.013518190942704678, -0.047120679169893265, 0.04077887162566185, -0.06109820306301117, -0.023814618587493896, -0.050725508481264114, 0.004147750791162252, 0.05331015959382057, -0.005132060497999191, 0.02387206442654133, 0.05782979354262352, -0.008879812434315681, -0.006859893910586834, -0.013202748261392117, 0.008315210230648518, 0.052713263779878616, -0.05233215168118477, 0.009968122467398643, 0.0006131050758995116, -0.03698724880814552, -0.004852973390370607, -0.05060683190822601, -0.05983230099081993, -0.06022332236170769, 0.030841033905744553, 0.08705291897058487, -0.04687225818634033, 0.03702192381024361, -0.011082918383181095, -0.0609256736934185, -0.046600837260484695, 0.03814627602696419, -0.0022243508137762547, 0.015714000910520554, 0.03299833461642265, -0.0014865935081616044, -0.05084230378270149, -0.03847359120845795, 0.029044058173894882, 0.009926743805408478, -0.023801175877451897, 0.04800756275653839, -0.0014094962971284986, -0.04117937386035919, 0.042356930673122406, 0.024763554334640503, -0.05951748415827751, -0.04960503429174423, -0.01772334799170494, 0.011049673892557621, 0.022265447303652763, -0.03712579980492592, 0.0007927537662908435, -0.034506626427173615, 0.01313430443406105, 0.009239297360181808, 0.03983595594763756, -0.028114022687077522, 0.029821764677762985, 0.046966005116701126, 0.0107656791806221, -0.05601649731397629, 0.015335945412516594, -0.025011684745550156, 0.022551970556378365, -0.0518459714949131, -0.03197074681520462, -0.03387906774878502, 0.0016889016842469573, -0.012036150321364403, 0.030316686257719994, -0.010381733067333698, 0.005567480344325304, 0.020053789019584656, -0.011086585931479931, 0.07029970735311508, 0.013899111188948154, -0.017137326300144196, -0.0017857452621683478, -0.02032710798084736, -0.05856867507100105, -0.037857845425605774, 0.0037797323893755674, 0.019799143075942993, 0.010910341516137123, -0.0582394115626812, 0.00828986894339323, 0.018351277336478233, -0.017176002264022827, 0.003597338916733861, -0.04992558807134628, -0.014108051545917988, -0.05257932469248772, -0.022051796317100525, -0.003697747830301523, -0.0008083399152383208, -0.021884415298700333, 0.027355652302503586, 0.001608899561688304, -0.029270872473716736, 0.00803724117577076, -0.012339362874627113, 0.006758160423487425, 0.005729360040277243, -0.0579100139439106, 0.03913363814353943, -0.016636686399579048, -0.04358697682619095, -0.02941569872200489, 0.025984136387705803, 0.015434686094522476, 0.0012913236860185862, -0.0316198505461216, 0.008551962673664093, -0.012817501090466976, 0.017244962975382805, -0.017946697771549225, 0.0075566391460597515, -0.017268847674131393, -0.013014265336096287, -0.002560192020609975, 0.030922340229153633, -0.008224988356232643, 0.05268019437789917, 0.003982068505138159, -0.010345794260501862, 0.033131081610918045, -0.0007086062687449157, -0.053183212876319885, 0.009540816769003868, 0.0024098914582282305, -0.02192230336368084, 0.03489076718688011, -0.02789459004998207, -0.030460786074399948, -0.043980296701192856, -0.049792107194662094, 0.028000403195619583, 0.01561665441840887, 0.008705420419573784, -0.030512064695358276, 0.023569263517856598, 0.009336842224001884, 0.04857616871595383, -0.01595386676490307, 0.02648543380200863, 0.017986230552196503, 0.006866452284157276, 0.009853449650108814, -0.025783957913517952, 0.028726406395435333, 0.03419651836156845, 0.020164841786026955, -0.046281181275844574, 0.001659324741922319, -0.03997606411576271, 0.020715588703751564, 0.03762338310480118, -0.025160690769553185, -0.02623177319765091, -0.050059087574481964, -0.035821810364723206, -0.0035403678193688393, 0.049556221812963486, 0.009503236040472984, -0.021995779126882553, 0.021978596225380898, -0.04644385352730751, -0.040550705045461655, 0.00851358100771904, -0.06697086244821548, 0.021348588168621063, 0.01528340857475996, 0.008236587047576904, -0.006347618065774441, -0.05902015045285225, -0.04722190648317337, 0.0062291971407830715, -0.019358281046152115, 0.013838451355695724, -0.0035466733388602734, 0.03502141684293747, -0.033088114112615585, 0.08082045614719391, -0.017953574657440186, -0.0033512453082948923, -0.0018916953122243285, 0.08003555983304977, -0.043224409222602844, 0.011126110330224037, -0.0014269870007410645, -0.0036793588660657406, 0.010767855681478977, -0.015071810223162174, 0.014763936400413513, 0.012500972487032413, 0.01468660682439804, 0.02249286323785782, -0.02419758215546608, 0.01778545044362545, -0.021458875387907028, 0.0175654087215662, 0.03144126757979393, -0.02325422316789627, -0.02611822821199894, 0.021155884489417076, 0.009579568170011044, 0.0013043694198131561, -0.07001358270645142, 0.033840764313936234, 0.039878711104393005, -0.007659215480089188, 0.050107065588235855, 0.02813653275370598, 0.06265097111463547, -0.016166895627975464, 0.014350788667798042, 0.009526500478386879, 0.04662127420306206, -0.010926062241196632, 0.021460482850670815, 0.015947097912430763, 0.012952819466590881, 0.031770188361406326, 0.0013197602238506079, -0.011859921738505363, 0.04229843243956566, 0.03402966633439064, -0.025654928758740425, -0.002025658031925559, 0.01061029452830553, 0.016096753999590874, -0.008174530230462551, 0.014449568465352058, -0.006015534978359938, 0.0039434004575014114, 0.006568399257957935, -0.0038125556893646717, 0.019119814038276672, 0.06984272599220276, -0.018593525514006615, -0.008790146559476852, -0.00018095348787028342, -0.025544114410877228, 0.03247366100549698, 0.0587841235101223, -0.00012888140918221325, 0.009333943016827106, 0.01293751411139965, 0.018684662878513336, -0.03726072981953621, 0.03305857628583908, 0.05203338712453842, -0.0010003657080233097, -0.027955666184425354, 0.0031926827505230904, 0.024860210716724396, -0.02947157248854637, -0.0427226647734642, -0.012206871062517166, -0.035350535064935684, 0.03083735704421997, -0.01065860129892826, -0.002102561527863145, 0.06250826269388199, -0.05243202671408653, -0.013654329814016819, -0.08047977834939957, 0.03372148051857948, -0.04058969393372536, 0.011458136141300201, 0.035233329981565475, 0.010580700822174549, -0.017640111967921257, -0.0037287729792296886, 0.01675143837928772, 0.042261023074388504, -0.01691362075507641, 0.014255553483963013, -0.05057903751730919, 0.028961503878235817, 0.011759067885577679, -0.027686186134815216, -0.032204411923885345, 0.034516409039497375, -0.0052967374213039875, -0.045915938913822174, -0.004560516681522131, -0.04469607397913933, -5.723511640098877e-05, -0.021578742191195488, -0.030068790540099144, 0.0028951517306268215, 0.03491724282503128, -0.01973828487098217, -0.05615050345659256, -0.010857718996703625, 0.009235871955752373, -0.07282894104719162, 0.012966232374310493, 0.004844010807573795, 0.030470198020339012, 0.013036316260695457, -0.0070401630364358425, -0.05429765209555626, -0.031917840242385864, -0.014532040804624557, -0.009927047416567802, 0.05188415199518204, -0.012942470610141754, -1.943316965480335e-05, -0.028560632839798927, -0.035566527396440506, -0.039553623646497726, -0.03119312785565853, 0.0039594536647200584, -0.03935719653964043, 0.0461106076836586, 0.056215181946754456, -0.0005066833691671491, -0.014445992186665535, -0.0038716914132237434, -0.011317883618175983, -0.01068265363574028, 0.041

[]

In [ ]:
collection

Collection(Database(MongoClient(host=['ac-mc5oagt-shard-00-02.rus2ded.mongodb.net:27017', 'ac-mc5oagt-shard-00-00.rus2ded.mongodb.net:27017', 'ac-mc5oagt-shard-00-01.rus2ded.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', appname='Cluster0', authsource='admin', replicaset='atlas-gu114m-shard-0', tls=True, server_api=<pymongo.server_api.ServerApi object at 0x0000024BE61B1C90>), 'mongorag'), 'mongoragcollection')

In [ ]:
query = "what is the best horror movie to watch and why?"

In [ ]:
def get_search_result(query,collection):

  get_knowledge=vector_search(query,collection)

  search_result=""

  for result in get_knowledge:
        search_result += f"Title: {result.get('title', 'N/A')}, Plot: {result.get('fullplot', 'N/A')}\n"

  return search_result

In [ ]:
source_information=get_search_result(query,collection)

[0.019185921177268028, -0.015472998842597008, -0.03955463692545891, 0.002369282301515341, -0.0026591995265334845, 0.005181849468499422, -0.007513169664889574, 0.04510665312409401, -0.018112152814865112, 0.042973391711711884, 0.01343401987105608, -0.0028707829769700766, 0.005479617975652218, -0.031249191612005234, -0.0040832762606441975, -0.031060393899679184, -0.04105724021792412, -0.030109740793704987, -0.03216371312737465, 0.027480358257889748, -0.0031675698701292276, 0.01684349775314331, -0.04414497688412666, -0.02399815246462822, -0.015581835061311722, 0.017874479293823242, 0.02161523886024952, -0.03042467124760151, 0.04588271304965019, 0.07223066687583923, 0.0023236689157783985, -0.04596634581685066, 0.026177139952778816, -0.048973821103572845, -0.03348345682024956, -0.010094995610415936, 0.0548892468214035, 0.0015839148545637727, -0.0027255131863057613, -0.038032565265893936, 0.01665717177093029, 0.014302357099950314, 0.04556028172373772, -0.011216177605092525, -0.05046369507908821, 0.0023861045483499765, 0.017925534397363663, -0.030081860721111298, -0.007713163737207651, -0.021677710115909576, 0.0025280362460762262, -0.03760185092687607, 0.011060122400522232, 0.006693254690617323, 0.013570711016654968, 0.02686602994799614, -0.011295484378933907, -0.013143062591552734, 0.00019356614211574197, 0.04410506412386894, 0.021538356319069862, -0.021799027919769287, 0.024568935856223106, -0.0283063892275095, 0.015344264917075634, 0.024441977962851524, 0.010560423135757446, -0.030671698972582817, 0.028781559318304062, 0.033182621002197266, 0.01933882012963295, -0.0029937559738755226, -0.019163787364959717, 0.01936383917927742, 0.01144575234502554, 0.02072315104305744, -0.01135884877294302, 0.027792207896709442, -0.015587683767080307, -0.020335961133241653, 0.01052192971110344, 0.05448819324374199, 0.021207375451922417, 0.015374410897493362, -0.0703800767660141, -0.04530000314116478, -0.017124861478805542, 0.02929656207561493, -0.014126786030828953, 0.0382278673350811, 0.03566664457321167, 0.027214163914322853, 0.011118213646113873, -0.032380275428295135, 0.04557011276483536, 0.05568910390138626, -0.03874795138835907, -0.005883869715034962, 0.0031911595724523067, -0.017282329499721527, 0.005285183433443308, 0.04445952922105789, -0.0044273920357227325, 0.028387324884533882, -0.03157701715826988, -0.005482749547809362, 0.02533877082169056, -0.004885320086032152, -0.024914715439081192, -0.05109068751335144, -0.007489930838346481, -0.036728985607624054, 0.00919526256620884, 0.010751624591648579, -0.011365924961864948, 0.03295490890741348, -0.004312330391258001, 0.04387517273426056, -0.059020426124334335, 0.02311747521162033, 0.01511062029749155, -0.00029512454057112336, 0.054292403161525726, -0.031850673258304596, 0.05932876095175743, -0.04194685444235802, -0.007042129524052143, 0.03700248524546623, -0.03655996173620224, -0.006839779671281576, -0.002326343907043338, -0.02935059554874897, 0.0031672262120991945, 0.04241705685853958, 0.01748664677143097, 0.015422792173922062, -0.0034261082764714956, -0.0076525029726326466, 0.024394555017352104, -0.051861438900232315, 0.042092952877283096, 0.006301604676991701, 0.008150339126586914, 0.07824896275997162, 0.007197103463113308, -0.008467086590826511, 0.018384108319878578, -0.008630882948637009, -0.008001118898391724, 0.03481711819767952, -0.0060943919233977795, 0.0023830533027648926, 0.005015701986849308, 0.018067052587866783, -0.01355196163058281, -0.023615287616848946, -0.021410604938864708, 0.020231517031788826, 0.00884122122079134, 0.06210235878825188, 0.04051230102777481, 0.022513380274176598, -0.03465414419770241, 0.038845986127853394, -0.002171834697946906, 0.04867856204509735, -0.03257758915424347, 0.0009074633126147091, -0.009817041456699371, -0.021265944465994835, 0.012817604467272758, 0.0042138793505728245, 0.008234729990363121, 0.001695835031569004, 0.03009480983018875, 0.04801255464553833, 0.048210375010967255, -0.035710450261831284, 0.024411767721176147, 0.04366959258913994, -0.028004730120301247, -0.008881084620952606, -0.014628280885517597, 0.08361643552780151, -0.014546838589012623, -0.023770932108163834, 0.0073107341304421425, -0.03333678096532822, -0.05331195145845413, -0.02066359855234623, -0.041558463126420975, 0.019447259604930878, -0.019201606512069702, 0.02138744294643402, 0.02292053960263729, 0.011376447975635529, -0.029181551188230515, -0.016784409061074257, -0.00248627457767725, -0.047684863209724426, -0.007824837230145931, 0.07042431086301804, -0.036518655717372894, 0.02187480218708515, 0.011032809503376484, -0.03732702508568764, 0.04041549935936928, 0.06125478446483612, -0.023774513974785805, -0.024698428809642792, 0.03328126668930054, 0.008721892721951008, 0.013296395540237427, 0.010940203443169594, -0.02857414446771145, 0.011603822000324726, -0.016490280628204346, 0.049017563462257385, -0.03695855662226677, 0.035665638744831085, -0.02091248333454132, 0.010374167934060097, 0.018073899671435356, 0.04076731950044632, 0.010249384678900242, -0.006932951509952545, 0.013178304769098759, 0.030500726774334908, -0.023781869560480118, 0.022923998534679413, 0.015516059473156929, 0.04982244223356247, 0.03889411687850952, 0.0416928268969059, 0.02739415504038334, 0.0071804821491241455, 0.04679451137781143, 0.021840013563632965, -0.011140125803649426, 0.03564215078949928, -0.021420788019895554, -0.004743363708257675, 0.03576232120394707, 0.04442800208926201, -0.024436917155981064, 0.02608756348490715, -0.028007710352540016, -0.025138041004538536, -0.036268316209316254, 0.02224046178162098, 0.02108948305249214, 0.025470666587352753, 0.03871040791273117, 0.01086736936122179, -0.01682245172560215, 0.0210602767765522, 0.03350116312503815, 0.06531915813684464, -0.005692128092050552, -0.0059856814332306385, -0.030677352100610733, 0.015677155926823616, 0.0317133404314518, 0.02010064572095871, 0.053008291870355606, 0.007643838878720999, -0.0057911742478609085, 0.01235566008836031, -0.055790212005376816, -0.07652189582586288, -0.03582770749926567, -0.04225977510213852, -0.012948219664394855, -0.04300167039036751, -0.038529835641384125, -0.002527671167626977, 0.029900675639510155, -0.02224842831492424, -0.001700952067039907, -0.015184932388365269, -0.02591577358543873, 0.0060766031965613365, -0.01386896800249815, 0.026459619402885437, -0.01826385036110878, 0.03126632049679756, -0.03586892411112785, 0.03716657683253288, -0.03319908678531647, 0.04537452757358551, -0.021382804960012436, -0.004415787290781736, 0.006134619005024433, 0.019581574946641922, 0.04254361614584923, 0.0059051490388810635, -0.029164308682084084, -0.022568175569176674, -0.022875305265188217, -0.06647871434688568, 0.022639112547039986, -0.0113392174243927, -0.014716237783432007, 0.012011069804430008, -0.0172160305082798, 0.0434841550886631, 0.03488685563206673, -0.01645171083509922, 0.031356435269117355, 0.023803835734725, -0.05105474218726158, 0.025596443563699722, -0.005357310175895691, 0.01876199059188366, -0.047838833183050156, 0.06260152906179428, 0.0211440809071064, -2.0024681361974217e-05, -0.005312437191605568, 0.02083437703549862, -0.017486901953816414, 0.0018560526659712195, 0.009527318179607391, -0.019396262243390083, -0.025708546862006187, 0.05055324360728264, 0.00716075673699379, -0.04304550215601921, 0.018376996740698814, -0.008618184365332127, 0.00033190479734912515, -0.01826566830277443, -0.03617510199546814, 0.051165368407964706, 0.03828044980764389, 0.05426185578107834, -0.03646084666252136, -0.039008382707834244, -0.02884177677333355, 0.034725796431303024, 0.04036794975399971, -0.017953302711248398, 0.009746535681188107, 0.04721890762448311, 0.01202540472149849, 0.025486785918474197, 0.0011297640157863498, -0.008161713369190693, 0.019771413877606392, 0.007591717876493931, -0.003687323071062565, -0.004959994927048683, 0.01181277446448803, -0.015729565173387527, 0.027522731572389603, 0.03859474137425423, -0.042433083057403564, 0.046922434121370316, 0.0038519178051501513, 0.012147344648838043, 0.029792310670018196, 0.013567662797868252, -0.008446097373962402, -0.010814509354531765, -0.04356779903173447, -0.06818488985300064, 0.031955428421497345, -0.01577688753604889, 0.05179140344262123, -0.058163441717624664, 0.06111203506588936, 0.011737610213458538, -0.035533878952264786, 0.0391046367585659, -0.024787291884422302, 0.024080991744995117, -0.007841079495847225, -0.01716063730418682, 0.014096200466156006, -0.025531869381666183, 0.005327623803168535, -0.017433155328035355, 0.06304162740707397, 0.07543289661407471, 0.01571950688958168, 0.054014116525650024, -0.02724122256040573, -0.050427768379449844, -0.02549748495221138, 0.0015442747389897704, 0.004260028712451458, -0.035203658044338226, 0.05002293363213539, -0.023227551952004433, -0.08523961901664734, -0.0465489998459816, 0.029208986088633537, 0.03454216197133064, 0.02241295762360096, -0.029873501509428024, 0.00015726308629382402, -0.005502286832779646, -0.014290652237832546, 0.034294720739126205, -0.0019598742946982384, 0.038172103464603424, -0.016469940543174744, 0.045612040907144547, -0.00666686100885272, -0.015410522930324078, -0.01791660115122795, -0.012537559494376183, -0.053635917603969574, 0.0453588105738163, -0.0029234918765723705, -0.009041969664394855, -0.012383061461150646, 0.011324063874781132, 0.03547552227973938, 0.02181280218064785, -0.019498148933053017, 0.011525538749992847, -0.012559996917843819, 0.02860092744231224, 0.005268723703920841, -0.07287371158599854, -0.01464419811964035, -0.0354132242500782, 0.05065648630261421, 0.04908342286944389, 0.011445136740803719, -0.03525003045797348, 0.00430272938683629, -0.031497396528720856, -0.0645153746008873, 0.010592910461127758, 0.05078413337469101, -0.02562553621828556, 0.03679646551609039, -0.05012014880776405, 0.015974821522831917, 0.00276441453024745, 0.0015346566215157509, -0.0077170622535049915, -0.012568357400596142, 0.028139842674136162, 0.0323764868080616, 0.024113377556204796, -0.0008314937585964799, -0.016307150945067406, -0.01156257838010788, -0.07263292372226715, 0.0011903343256562948, 0.02266848087310791, -0.03263675794005394, 0.03516516834497452, 0.030683083459734917, 0.01946829818189144, 0.0435185581445694, -0.01727808080613613, 0.07233164459466934, -0.05512724071741104, 0.036221180111169815, -0.023955469951033592, -0.04078449308872223, 0.051093947142362595, 0.026091711595654488, -0.022817695513367653, 0.050516702234745026, 0.0011860346421599388, 0.0019683160353451967, -0.009243431501090527, 0.049235936254262924, -0.0470174178481102, 0.04077018052339554, -0.040767453610897064, 0.0051933773793280125, 0.016194460913538933, -0.035089172422885895, 0.015681913122534752, -0.03688392415642738, 0.026260720565915108, 0.014252346940338612, 0.02244764193892479, -0.04101819545030594, -0.034034423530101776, -0.023256046697497368, -0.037091322243213654, 0.0033504993189126253, -0.0058056931011378765, 0.020454689860343933, 0.015604528598487377, -0.022060319781303406, -0.020030658692121506, -0.018010569736361504, 0.0007797750877216458, 0.007693904917687178, 0.02321474999189377, -0.013181624002754688, 0.029439959675073624, -0.009283574298024178, -0.01701640523970127, -0.021441560238599777, -0.004634247627109289, 0.015105959959328175, -0.027900248765945435, -0.04936208575963974, 0.004174375906586647, -0.03569092974066734, -0.007284390274435282, -0.03441615775227547, 0.0171204824000597, -0.05422945320606232, 0.06041432172060013, 0.0069463131949305534, 0.0411558598279953, -0.0033390820026397705, -0.006697501055896282, -0.024914389476180077, 0.04574881121516228, 0.010451887734234333, -0.029245223850011826, -0.02555392123758793, 0.0348367877304554, -0.021192556247115135, 0.03171221911907196, -0.010004832409322262, -0.016670292243361473, -0.09865675121545792, -0.030303392559289932, 0.011668228544294834, -0.038203127682209015, 0.0028980113565921783, -0.03496034815907478, -0.032910093665122986, -0.020274197682738304, 0.017710406333208084, 0.002595791593194008, 0.004258854314684868, -0.004389781504869461, -0.011577245779335499, -0.02874322608113289, -0.0007525589899159968, -0.03422609344124794, -0.028095170855522156, 0.005800566170364618, -0.005880630109459162, 0.06386711448431015, -0.006240864284336567, 0.04142501950263977, 0.001961540197953582, 0.030961986631155014, 0.024950897321105003, -0.010406777262687683, -0.05980537459254265, -0.01057790033519268, 0.009262622334063053, -0.004312954843044281, -0.02315055951476097, 0.02365650236606598, -0.054919201880693436, 0.011977684684097767, -0.0437474399805069, 0.010738398879766464, -0.008227531798183918, -0.024477191269397736, 0.002058612182736397, 0.008173737674951553, 0.06306764483451843, -0.032219238579273224, -0.02305232733488083, 0.002410921733826399, 0.04274039342999458, 0.0897863581776619, 0.0028557186014950275, -0.03453759849071503, -0.030182495713233948, -0.013518190942704678, -0.047120679169893265, 0.04077887162566185, -0.06109820306301117, -0.023814618587493896, -0.050725508481264114, 0.004147750791162252, 0.05331015959382057, -0.005132060497999191, 0.02387206442654133, 0.05782979354262352, -0.008879812434315681, -0.006859893910586834, -0.013202748261392117, 0.008315210230648518, 0.052713263779878616, -0.05233215168118477, 0.009968122467398643, 0.0006131050758995116, -0.03698724880814552, -0.004852973390370607, -0.05060683190822601, -0.05983230099081993, -0.06022332236170769, 0.030841033905744553, 0.08705291897058487, -0.04687225818634033, 0.03702192381024361, -0.011082918383181095, -0.0609256736934185, -0.046600837260484695, 0.03814627602696419, -0.0022243508137762547, 0.015714000910520554, 0.03299833461642265, -0.0014865935081616044, -0.05084230378270149, -0.03847359120845795, 0.029044058173894882, 0.009926743805408478, -0.023801175877451897, 0.04800756275653839, -0.0014094962971284986, -0.04117937386035919, 0.042356930673122406, 0.024763554334640503, -0.05951748415827751, -0.04960503429174423, -0.01772334799170494, 0.011049673892557621, 0.022265447303652763, -0.03712579980492592, 0.0007927537662908435, -0.034506626427173615, 0.01313430443406105, 0.009239297360181808, 0.03983595594763756, -0.028114022687077522, 0.029821764677762985, 0.046966005116701126, 0.0107656791806221, -0.05601649731397629, 0.015335945412516594, -0.025011684745550156, 0.022551970556378365, -0.0518459714949131, -0.03197074681520462, -0.03387906774878502, 0.0016889016842469573, -0.012036150321364403, 0.030316686257719994, -0.010381733067333698, 0.005567480344325304, 0.020053789019584656, -0.011086585931479931, 0.07029970735311508, 0.013899111188948154, -0.017137326300144196, -0.0017857452621683478, -0.02032710798084736, -0.05856867507100105, -0.037857845425605774, 0.0037797323893755674, 0.019799143075942993, 0.010910341516137123, -0.0582394115626812, 0.00828986894339323, 0.018351277336478233, -0.017176002264022827, 0.003597338916733861, -0.04992558807134628, -0.014108051545917988, -0.05257932469248772, -0.022051796317100525, -0.003697747830301523, -0.0008083399152383208, -0.021884415298700333, 0.027355652302503586, 0.001608899561688304, -0.029270872473716736, 0.00803724117577076, -0.012339362874627113, 0.006758160423487425, 0.005729360040277243, -0.0579100139439106, 0.03913363814353943, -0.016636686399579048, -0.04358697682619095, -0.02941569872200489, 0.025984136387705803, 0.015434686094522476, 0.0012913236860185862, -0.0316198505461216, 0.008551962673664093, -0.012817501090466976, 0.017244962975382805, -0.017946697771549225, 0.0075566391460597515, -0.017268847674131393, -0.013014265336096287, -0.002560192020609975, 0.030922340229153633, -0.008224988356232643, 0.05268019437789917, 0.003982068505138159, -0.010345794260501862, 0.033131081610918045, -0.0007086062687449157, -0.053183212876319885, 0.009540816769003868, 0.0024098914582282305, -0.02192230336368084, 0.03489076718688011, -0.02789459004998207, -0.030460786074399948, -0.043980296701192856, -0.049792107194662094, 0.028000403195619583, 0.01561665441840887, 0.008705420419573784, -0.030512064695358276, 0.023569263517856598, 0.009336842224001884, 0.04857616871595383, -0.01595386676490307, 0.02648543380200863, 0.017986230552196503, 0.006866452284157276, 0.009853449650108814, -0.025783957913517952, 0.028726406395435333, 0.03419651836156845, 0.020164841786026955, -0.046281181275844574, 0.001659324741922319, -0.03997606411576271, 0.020715588703751564, 0.03762338310480118, -0.025160690769553185, -0.02623177319765091, -0.050059087574481964, -0.035821810364723206, -0.0035403678193688393, 0.049556221812963486, 0.009503236040472984, -0.021995779126882553, 0.021978596225380898, -0.04644385352730751, -0.040550705045461655, 0.00851358100771904, -0.06697086244821548, 0.021348588168621063, 0.01528340857475996, 0.008236587047576904, -0.006347618065774441, -0.05902015045285225, -0.04722190648317337, 0.0062291971407830715, -0.019358281046152115, 0.013838451355695724, -0.0035466733388602734, 0.03502141684293747, -0.033088114112615585, 0.08082045614719391, -0.017953574657440186, -0.0033512453082948923, -0.0018916953122243285, 0.08003555983304977, -0.043224409222602844, 0.011126110330224037, -0.0014269870007410645, -0.0036793588660657406, 0.010767855681478977, -0.015071810223162174, 0.014763936400413513, 0.012500972487032413, 0.01468660682439804, 0.02249286323785782, -0.02419758215546608, 0.01778545044362545, -0.021458875387907028, 0.0175654087215662, 0.03144126757979393, -0.02325422316789627, -0.02611822821199894, 0.021155884489417076, 0.009579568170011044, 0.0013043694198131561, -0.07001358270645142, 0.033840764313936234, 0.039878711104393005, -0.007659215480089188, 0.050107065588235855, 0.02813653275370598, 0.06265097111463547, -0.016166895627975464, 0.014350788667798042, 0.009526500478386879, 0.04662127420306206, -0.010926062241196632, 0.021460482850670815, 0.015947097912430763, 0.012952819466590881, 0.031770188361406326, 0.0013197602238506079, -0.011859921738505363, 0.04229843243956566, 0.03402966633439064, -0.025654928758740425, -0.002025658031925559, 0.01061029452830553, 0.016096753999590874, -0.008174530230462551, 0.014449568465352058, -0.006015534978359938, 0.0039434004575014114, 0.006568399257957935, -0.0038125556893646717, 0.019119814038276672, 0.06984272599220276, -0.018593525514006615, -0.008790146559476852, -0.00018095348787028342, -0.025544114410877228, 0.03247366100549698, 0.0587841235101223, -0.00012888140918221325, 0.009333943016827106, 0.01293751411139965, 0.018684662878513336, -0.03726072981953621, 0.03305857628583908, 0.05203338712453842, -0.0010003657080233097, -0.027955666184425354, 0.0031926827505230904, 0.024860210716724396, -0.02947157248854637, -0.0427226647734642, -0.012206871062517166, -0.035350535064935684, 0.03083735704421997, -0.01065860129892826, -0.002102561527863145, 0.06250826269388199, -0.05243202671408653, -0.013654329814016819, -0.08047977834939957, 0.03372148051857948, -0.04058969393372536, 0.011458136141300201, 0.035233329981565475, 0.010580700822174549, -0.017640111967921257, -0.0037287729792296886, 0.01675143837928772, 0.042261023074388504, -0.01691362075507641, 0.014255553483963013, -0.05057903751730919, 0.028961503878235817, 0.011759067885577679, -0.027686186134815216, -0.032204411923885345, 0.034516409039497375, -0.0052967374213039875, -0.045915938913822174, -0.004560516681522131, -0.04469607397913933, -5.723511640098877e-05, -0.021578742191195488, -0.030068790540099144, 0.0028951517306268215, 0.03491724282503128, -0.01973828487098217, -0.05615050345659256, -0.010857718996703625, 0.009235871955752373, -0.07282894104719162, 0.012966232374310493, 0.004844010807573795, 0.030470198020339012, 0.013036316260695457, -0.0070401630364358425, -0.05429765209555626, -0.031917840242385864, -0.014532040804624557, -0.009927047416567802, 0.05188415199518204, -0.012942470610141754, -1.943316965480335e-05, -0.028560632839798927, -0.035566527396440506, -0.039553623646497726, -0.03119312785565853, 0.0039594536647200584, -0.03935719653964043, 0.0461106076836586, 0.056215181946754456, -0.0005066833691671491, -0.014445992186665535, -0.0038716914132237434, -0.011317883618175983, -0.01068265363574028, 0.041

In [ ]:
combined_information = f"Query: {query}\nContinue to answer the query by using the Search Results:\n{source_information}."

print(combined_information)

Query: what is the best horror movie to watch and why?
Continue to answer the query by using the Search Results:
.

In [ ]:
user_query="what is the best horror movie?"

In [ ]:
query_embedding=get_embedding(user_query)

In [ ]:
pipeline = [

    {
        "$vectorSearch": {
            "index": "vector_index",
            "queryVector": query_embedding,
            "path": "embedding",
            "numCandidates": 150,  # Number of candidate matches to consider
            "limit": 4,  # Return top 4 matches
        }
    },
    {
        "$project": {
            "fullplot": 1,  # Include the plot field
            "title": 1,  # Include the title field
            "genres": 1,  # Include the genres field
            "score": {"$meta": "vectorSearchScore"},  # Include the search score
        }
    }
]